import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml' | 'mr' | 'bn' | 'or' | 'gu';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeName: 'English' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা' },
  { code: 'or', label: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Tabs
    tab_dashboard: 'Dashboard',
    tab_praman_ai: 'Praman AI',
    tab_standards: 'Standards',
    tab_services: 'Services',
    tab_nabl_labs: 'NABL labs',
    tab_enterprise: 'Enterprise',

    // Dashboard
    greeting_title: 'Good evening, Sripathi',
    greeting_sub: 'BIS licensee dashboard',
    enterprise_status: 'ENTERPRISE COMPLIANCE STATUS',
    qco_compliant: 'QCO compliant',
    registered_facility: 'Registered facility',
    certified_product_lines: 'Certified product lines · 2 active ISI licenses',
    two_wheeler_helmets: 'Two-wheeler helmets',
    stainless_steel_flasks: 'Stainless steel flasks and water bottles',
    valid_2027: 'Valid 2027',
    valid_2026: 'Valid 2026',
    manage_enterprise: 'Manage enterprise credentials and officer details',
    ask_praman_badge: 'AI compliance assistant',
    live_gazette_sync: 'Live gazette sync',
    ask_praman_title: 'Ask Praman compliance assistant',
    ask_praman_sub: 'Ask in Indian languages. Instant retrieval from official BIS gazettes, QCOs, and testing scopes.',
    search_praman_placeholder: 'Ask about IS 4151, mandatory QCOs, or nearest lab',
    quick_regulatory_services: 'Quick regulatory services',
    qco_checker_title: 'QCO & Standards Checker',
    qco_checker_badge: 'MANDATORY',
    qco_checker_sub: 'Search 14,000+ Indian standards & mandatory gazettes',
    doc_vault_title: 'Document Vault',
    doc_vault_badge: '3 CREDENTIALS',
    doc_vault_sub: '3 verified certificates & NABL test reports',
    labs_dir_title: 'All-India Testing Labs Directory',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'Find accredited test facilities by product and city',
    services_programmes_title: 'BIS Services & Programmes',
    services_programmes_badge: 'SCHEMES',
    services_programmes_sub: 'Standards Clubs, NITS training, LRS lab scheme & certification',
    consumer_corner_title: 'Consumer Protection & Grievance Corner',
    national_consumer_helpline: 'National Consumer Helpline',
    toll_free: '1800-11-4000 (Toll-Free)',
    call_now: 'Call Now',
    consumer_card_desc: 'Report spurious ISI marks, substandard goods, or gold jewellery sold without mandatory 6-digit HUID code directly to BIS enforcement.',
    bis_grievance_portal: 'BIS Grievance Portal',
    download_bis_care: 'Download BIS CARE App',
    chip_helmets: 'IS 4151 helmets',
    chip_gold: 'Gold hallmark & HUID',
    chip_labs: 'Find NABL labs',

    // Praman AI
    praman_header_title: 'Praman compliance assistant',
    praman_header_sub: 'Official BIS regulatory knowledge base',
    auto_lang_banner: 'Auto language detection active · English, Hindi, Tamil, Telugu, Kannada, Malayalam, Marathi, Bengali, Odia, Gujarati',
    praman_welcome: 'Hello, I am Praman, your Bureau of Indian Standards compliance assistant. You can ask in English, Hindi, Tamil, Telugu, Kannada, Malayalam, Marathi, Bengali, Odia, or Gujarati.\n\nEvery response is retrieved from official BIS gazettes, DPIIT QCO orders, and NABL testing protocols.',
    ask_input_placeholder: 'Ask in English, Hindi, Tamil, Telugu, Kannada...',
    chat_sessions: 'Chat Sessions',
    new_chat: 'New Chat',
    pinned_chats: 'PINNED CHATS',
    recent_chats: 'RECENT CHATS',
    pin_chat: 'Pin',
    unpin_chat: 'Unpin',
    rename_chat: 'Rename',
    delete_chat: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    rename_chat_title: 'Rename Chat Session',
    enter_new_title: 'Enter new title for this chat',
    no_chats_found: 'No saved chat sessions',

    // Standards
    standards_title: 'Standards and QCO verification',
    standards_sub: 'Official Bureau of Indian Standards registry and quality control orders',
    verify_compliance_prompt: 'Verify product compliance and mandatory standards',
    standards_input_placeholder: 'e.g. Helmet, IS 4151, Stainless steel bottle, Plugs',
    run_qco_check_btn: 'Run QCO knowledge graph check',
    jurisdiction_label: 'REGULATORY JURISDICTION AND ENFORCEMENT ZONE',
    change_zone_btn: 'Change zone',
    jurisdiction_desc: 'This setting configures your designated BIS branch office for annual surveillance audits, aligns state gazette enforcement cutoffs, and prioritizes third-party NABL testing laboratories within 250 km.',
    division_councils_title: 'BIS standards division councils',
    division_councils_sub: '8 central technical divisions · 14,000+ Indian standards',
    standards_count_suffix: 'standards',

    // Services
    services_badge: 'Official BIS programmes and schemes',
    services_title: 'Bureau of Indian Standards services',
    services_sub: 'Explore key government initiatives across product certification, standards clubs in academia, professional NITS training, NABL lab empanelment, and consumer affairs.',
    target_eligibility: 'TARGET ELIGIBILITY',
    open_scheme_portal: 'Open official scheme portal',

    // NABL Labs
    labs_title: 'All-India testing laboratories directory',
    labs_sub: 'Official BIS-recognized and NABL-accredited (ISO/IEC 17025) testing facilities across India',
    current_facility_label: 'YOUR CURRENT REGISTERED FACILITY',
    primary_facility_badge: 'Primary facility',
    filter_region: 'Filter by region / state',
    filter_scope: 'Filter by product testing scope',
    showing_facilities: 'Showing accredited facilities',
    near_you: 'Near you',
    proximity: 'Proximity',
    accredited_scope_label: 'ACCREDITED TESTING SCOPE',
    open_google_maps: 'Open in Google Maps',

    // Settings
    settings_title: 'Settings & Preferences',
    app_language_title: 'App Language & Interface Dialect',
    app_language_sub: 'Sets the default app display language across all pages.',
    notifications_title: 'Notification Preferences',
    gazette_alerts: 'QCO Gazette Mandate Alerts',
    gazette_alerts_sub: 'Instant push alert when DPIIT/MoRTH issues new standards',
    audit_reminders: 'Surveillance Audit Reminders',
    audit_reminders_sub: 'Quarterly reminders for factory testing records and sample submissions',
    back: 'Back',

    // Profile
    profile_title: 'Enterprise Credentials',
    profile_sub: 'BIS Licensee Registry & Compliance Records',
    tab_licenses: 'Licenses',
    tab_audit: 'Audit & Visits',
    tab_officer: 'BIS Officer',
    audit_score: 'Audit Score',
    active_licenses: 'Active Licenses',
    next_surveillance: 'Next Surveillance',
    factory_premises: 'Factory Premises',
    auth_signatory: 'Authorized Signatory',
    factory_unit: 'Factory Unit',
    lab_clearance: 'Lab Clearance',
    surveillance_visit: 'Surveillance Visit',
    view_license_cert: 'View License Certificate',
    standard_specs: 'Standard Specifications',
    next_audit_title: 'Next Audit: 18-Nov-2024',
    surveillance_desc: 'Surveillance inspection for IS 4151 (Two-Wheeler Helmets) scheduled by CNBO. Maintain test logs and factory calibration registers in the Document Vault.',
    prepare_audit_docs: 'Prepare Audit Documents',
    compliance_lifecycle: 'Compliance Lifecycle',
    branch_office: 'Branch Office',
    office_hours: 'Office Hours',
    email_branch: 'Email Branch',

    // Ask Extra
    chip_prompt_helmet: 'Two-wheeler helmet standard IS 4151',
    chip_prompt_bottle: 'Verify stainless steel bottle IS 17803',
    chip_prompt_labs: 'Testing laboratories in Chennai',
    chip_prompt_fake_isi: 'How to check counterfeit ISI mark',
    chip_prompt_hallmark: 'Gold hallmark & HUID verification',
    chip_prompt_complaint: 'File consumer complaint 1800-11-4000',
    praman_disclaimer: 'Assistive only. Official verification on BIS CARE or bis.gov.in.',

    // Standards Extra
    resolved_classification: 'RESOLVED CLASSIFICATION',
    applicable_standard: 'APPLICABLE STANDARD',
    certification_scheme: 'CERTIFICATION SCHEME',
    enforcing_authority: 'Enforcing authority and gazette:',
    mandatory_testing_scope: 'Mandatory testing scope:',
    open_bis_registry: 'Open official BIS standard registry page',
    related_standards: 'RELATED AND CROSS-REFERENCED STANDARDS',

    // Services Extra
    cat_all: 'All',
    cat_industry: 'Industry and manufacturing',
    cat_youth: 'Youth and academia',
    cat_capacity: 'Capacity building',
    cat_testing: 'Testing and calibration',
    cat_citizen: 'Citizen services',
    cat_digital: 'Digital verification',

    // Vault
    vault_title: 'Document Vault',
    upload_doc_title: 'Upload Certificate or Test Report',
    upload_doc_sub: 'PDF, JPG or PNG up to 15MB · Instant OCR extraction',
    stored_certs: 'Stored Certificates',
  },

  hi: {
    // Tabs
    tab_dashboard: 'डैशबोर्ड',
    tab_praman_ai: 'प्रमाण एआई',
    tab_standards: 'मानक',
    tab_services: 'सेवाएं',
    tab_nabl_labs: 'NABL प्रयोगशालाएं',
    tab_enterprise: 'उद्यम',

    // Dashboard
    greeting_title: 'शुभ संध्या, श्रीपति',
    greeting_sub: 'बीआईएस लाइसेंसधारी डैशबोर्ड',
    enterprise_status: 'उद्यम अनुपालन स्थिति',
    qco_compliant: 'QCO अनुपालन संपन्न',
    registered_facility: 'पंजीकृत संयंत्र',
    certified_product_lines: 'प्रमाणित उत्पाद श्रृंखलाएं · 2 सक्रिय ISI लाइसेंस',
    two_wheeler_helmets: 'दोपहिया हेलमेट',
    stainless_steel_flasks: 'स्टेनलेस स्टील फ्लास्क और पानी की बोतलें',
    valid_2027: 'वैध 2027',
    valid_2026: 'वैध 2026',
    manage_enterprise: 'उद्यम प्रमाण पत्र और अधिकारी विवरण प्रबंधित करें',
    ask_praman_badge: 'एआई अनुपालन सहायक',
    live_gazette_sync: 'लाइव राजपत्र सिंक',
    ask_praman_title: 'प्रमाण अनुपालन सहायक से पूछें',
    ask_praman_sub: 'भारतीय भाषाओं में पूछें। आधिकारिक बीआईएस राजपत्रों, क्यूसीओ और परीक्षण मानकों से त्वरित उत्तर।',
    search_praman_placeholder: 'IS 4151, अनिवार्य QCO या निकटतम लैब के बारे में पूछें',
    quick_regulatory_services: 'त्वरित नियामक सेवाएं',
    qco_checker_title: 'QCO और मानक चेकर',
    qco_checker_badge: 'अनिवार्य',
    qco_checker_sub: '14,000+ भारतीय मानक और राजपत्र खोजें',
    doc_vault_title: 'दस्तावेज़ वॉल्ट',
    doc_vault_badge: '3 प्रमाण पत्र',
    doc_vault_sub: '3 सत्यापित प्रमाणपत्र और NABL परीक्षण रिपोर्ट',

    // Praman AI
    praman_header_title: 'प्रमाण अनुपालन सहायक',
    praman_header_sub: 'आधिकारिक बीआईएस नियामक ज्ञानकोश',
    auto_lang_banner: 'स्वचालित भाषा पहचान सक्रिय · हिन्दी, अंग्रेजी, तमिल, तेलुगु, कन्नड़, मलयालम, मराठी, बांग्ला, ओडिया, गुजराती',
    praman_welcome: 'नमस्ते, मैं प्रमाण हूँ, आपका भारतीय मानक ब्यूरो अनुपालन सहायक। आप हिन्दी, अंग्रेजी, तमिल, तेलुगु, कन्नड़, मलयालम, मराठी, बांग्ला, ओडिया या गुजराती में पूछ सकते हैं।\n\nप्रत्येक उत्तर आधिकारिक बीआईएस राजपत्रों, डीपीआईआईटी क्यूसीओ आदेशों और एनएबीएल परीक्षण प्रोटोकॉल से प्राप्त होता है।',
    ask_input_placeholder: 'हिन्दी, अंग्रेजी, तमिल, तेलुगु में पूछें...',
    chat_sessions: 'चैट सत्र',
    new_chat: 'नई चैट',
    pinned_chats: 'पिन किए गए चैट',
    recent_chats: 'हाल के चैट',
    pin_chat: 'पिन करें',
    unpin_chat: 'अनपिन करें',
    rename_chat: 'नाम बदलें',
    delete_chat: 'हटाएं',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    rename_chat_title: 'चैट सत्र का नाम बदलें',
    enter_new_title: 'इस चैट के लिए नया शीर्षक दर्ज करें',
    no_chats_found: 'कोई सहेजा गया चैट सत्र नहीं मिला',

    // Standards
    standards_title: 'मानक और QCO सत्यापन',
    standards_sub: 'आधिकारिक भारतीय मानक ब्यूरो रजिस्ट्री और गुणवत्ता नियंत्रण आदेश',
    verify_compliance_prompt: 'उत्पाद अनुपालन और अनिवार्य मानकों को सत्यापित करें',
    standards_input_placeholder: 'जैसे हेलमेट, IS 4151, स्टेनलेस स्टील बोतल, प्लग',
    run_qco_check_btn: 'QCO ज्ञान ग्राफ जांच चलाएं',
    jurisdiction_label: 'नियामक अधिकार क्षेत्र और प्रवर्तन क्षेत्र',
    change_zone_btn: 'क्षेत्र बदलें',
    jurisdiction_desc: 'यह सेटिंग वार्षिक निगरानी ऑडिट के लिए आपके बीआईएस शाखा कार्यालय को निर्धारित करती है और 250 किमी के भीतर NABL प्रयोगशालाओं को प्राथमिकता देती है।',
    division_councils_title: 'बीआईएस मानक प्रभाग परिषदें',
    division_councils_sub: '8 केंद्रीय तकनीकी प्रभाग · 14,000+ भारतीय मानक',
    standards_count_suffix: 'मानक',

    // Services
    services_badge: 'आधिकारिक बीआईएस कार्यक्रम और योजनाएं',
    services_title: 'भारतीय मानक ब्यूरो सेवाएं',
    services_sub: 'उत्पाद प्रमाणन, मानकों के क्लब, पेशेवर प्रशिक्षण, और उपभोक्ता मामलों में सरकारी पहलों का अन्वेषण करें।',
    target_eligibility: 'पात्रता',
    open_scheme_portal: 'आधिकारिक योजना पोर्टल खोलें',

    // NABL Labs
    labs_title: 'अखिल भारतीय परीक्षण प्रयोगशाला निर्देशिका',
    labs_sub: 'भारत भर में आधिकारिक बीआईएस-मान्यता प्राप्त और एनएबीएल-प्रत्यायित परीक्षण सुविधाएं',
    current_facility_label: 'आपकी वर्तमान पंजीकृत सुविधा',
    primary_facility_badge: 'प्राथमिक सुविधा',
    filter_region: 'क्षेत्र / राज्य द्वारा फ़िल्टर करें',
    filter_scope: 'उत्पाद परीक्षण कार्यक्षेत्र द्वारा फ़िल्टर करें',
    showing_facilities: 'प्रत्यायित सुविधाएं प्रदर्शित हैं',
    near_you: 'आपके निकट',
    proximity: 'दूरी',
    accredited_scope_label: 'प्रत्यायित परीक्षण कार्यक्षेत्र',
    open_google_maps: 'गूगल मैप्स में खोलें',

    // Settings
    settings_title: 'सेटिंग्स और प्राथमिकताएं',
    app_language_title: 'ऐप भाषा और इंटरफ़ेस बोली',
    app_language_sub: 'सभी पृष्ठों पर डिफ़ॉल्ट ऐप प्रदर्शन भाषा सेट करता है।',
    notifications_title: 'अधिसूचना प्राथमिकताएं',
    gazette_alerts: 'QCO राजपत्र चेतावनी',
    gazette_alerts_sub: 'नए मानक जारी होने पर त्वरित पुश अलर्ट',
    audit_reminders: 'निगरानी ऑडिट अनुस्मारक',
    audit_reminders_sub: 'त्रैमासिक परीक्षण रिकॉर्ड के लिए अनुस्मारक',
    back: 'वापस',

    // Profile
    profile_title: 'उद्यम साख एवं रिकॉर्ड',
    profile_sub: 'बीआईएस लाइसेंसधारी रजिस्ट्री और अनुपालन रिकॉर्ड',
    tab_licenses: 'लाइसेंस',
    tab_audit: 'ऑडिट और निरीक्षण',
    tab_officer: 'बीआईएस अधिकारी',
    audit_score: 'ऑडिट स्कोर',
    active_licenses: 'सक्रिय लाइसेंस',
    next_surveillance: 'अगला निरीक्षण',
    factory_premises: 'संयंत्र परिसर',
    auth_signatory: 'अधिकृत हस्ताक्षरकर्ता',
    factory_unit: 'कारखाना इकाई',
    lab_clearance: 'लैब क्लीयरेंस',
    surveillance_visit: 'निगरानी निरीक्षण',
    view_license_cert: 'लाइसेंस प्रमाणपत्र देखें',
    standard_specs: 'मानक विनिर्देश',
    next_audit_title: 'अगला ऑडिट: 18-Nov-2024',
    surveillance_desc: 'सीएनबीओ द्वारा निर्धारित आईएस 4151 (हेलमेट) हेतु निगरानी निरीक्षण। दस्तावेज वॉल्ट में परीक्षण लॉग बनाए रखें।',
    prepare_audit_docs: 'ऑडिट दस्तावेज तैयार करें',
    compliance_lifecycle: 'अनुपालन जीवनचक्र',
    branch_office: 'शाखा कार्यालय',
    office_hours: 'कार्यालय समय',
    email_branch: 'शाखा को ईमेल करें',

    // Ask Extra
    chip_prompt_helmet: 'दोपहिया वाहन हेलमेट मानक IS 4151',
    chip_prompt_bottle: 'स्टेनलेस स्टील बोतल IS 17803 सत्यापित करें',
    chip_prompt_labs: 'चेन्नई में परीक्षण प्रयोगशालाएं',
    chip_prompt_fake_isi: 'नकली आईएसआई मार्क की जांच कैसे करें',
    chip_prompt_hallmark: 'स्वर्ण हॉलमार्क और HUID सत्यापन',
    chip_prompt_complaint: 'उपभोक्ता शिकायत दर्ज करें 1800-11-4000',
    praman_disclaimer: 'केवल सहायक। बीआईएस केयर या bis.gov.in पर आधिकारिक सत्यापन करें।',

    // Standards Extra
    resolved_classification: 'सत्यापित वर्गीकरण',
    applicable_standard: 'लागू मानक',
    certification_scheme: 'प्रमाणन योजना',
    enforcing_authority: 'प्रवर्तन प्राधिकरण और राजपत्र:',
    mandatory_testing_scope: 'अनिवार्य परीक्षण कार्यक्षेत्र:',
    open_bis_registry: 'आधिकारिक बीआईएस मानक रजिस्ट्री पृष्ठ खोलें',
    related_standards: 'संबंधित और संदर्भित मानक',

    // Services Extra
    cat_all: 'सभी',
    cat_industry: 'उद्योग और विनिर्माण',
    cat_youth: 'युवा और शिक्षा',
    cat_capacity: 'क्षमता निर्माण',
    cat_testing: 'परीक्षण और अंशांकन',
    cat_citizen: 'नागरिक सेवाएं',
    cat_digital: 'डिजिटल सत्यापन',

    // Vault
    vault_title: 'दस्तावेज़ वॉल्ट',
    upload_doc_title: 'प्रमाणपत्र या परीक्षण रिपोर्ट अपलोड करें',
    upload_doc_sub: 'पीडीएफ, जेपीजी या पीएनजी 15 एमबी तक · त्वरित ओसीआर',
    stored_certs: 'संग्रहीत प्रमाणपत्र',

    // Dashboard Extra
    labs_dir_title: 'अखिल भारतीय परीक्षण प्रयोगशाला निर्देशिका',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'उत्पाद और शहर के अनुसार मान्यता प्राप्त परीक्षण सुविधाएं खोजें',
    services_programmes_title: 'बीआईएस सेवाएं और कार्यक्रम',
    services_programmes_badge: 'योजनाएं',
    services_programmes_sub: 'मानक क्लब, एनआईटीएस प्रशिक्षण, एलआरएस लैब योजना और प्रमाणन',
    consumer_corner_title: 'उपभोक्ता संरक्षण और शिकायत कॉर्नर',
    national_consumer_helpline: 'राष्ट्रीय उपभोक्ता हेल्पलाइन',
    toll_free: '1800-11-4000 (टोल-फ्री)',
    call_now: 'कॉल करें',
    consumer_card_desc: 'नकली आईएसआई मार्क, घटिया सामान या अनिवार्य 6-अंकीय एचयूआईडी के बिना बेचे जाने वाले सोने के आभूषणों की सीधी रिपोर्ट करें।',
    bis_grievance_portal: 'बीआईएस शिकायत पोर्टल',
    download_bis_care: 'बीआईएस केयर ऐप डाउनलोड करें',
    chip_helmets: 'IS 4151 हेलमेट',
    chip_gold: 'स्वर्ण हॉलमार्क और HUID',
    chip_labs: 'NABL प्रयोगशालाएं खोजें',
  },

  ta: {
    // Tabs
    tab_dashboard: 'டாஷ்போர்டு',
    tab_praman_ai: 'பிரமாண் AI',
    tab_standards: 'தரநிலைகள்',
    tab_services: 'சேவைகள்',
    tab_nabl_labs: 'NABL ஆய்வகங்கள்',
    tab_enterprise: 'நிறுவனம்',

    // Dashboard
    greeting_title: 'மாலை வணக்கம், ஸ்ரீபதி',
    greeting_sub: 'BIS உரிமதாரர் டாஷ்போர்டு',
    enterprise_status: 'நிறுவன இணக்க நிலை',
    qco_compliant: 'QCO இணக்கமானது',
    registered_facility: 'பதிவுசெய்யப்பட்ட வசதி',
    certified_product_lines: 'சான்றளிக்கப்பட்ட பொருட்கள் · 2 செயலில் உள்ள ISI உரிமங்கள்',
    two_wheeler_helmets: 'இருசக்கர வாகன ஹெல்மெட்கள்',
    stainless_steel_flasks: 'துருப்பிடிக்காத எஃகு பிளாஸ்க்குகள் & பாட்டில்கள்',
    valid_2027: '2027 வரை செல்லுபடியாகும்',
    valid_2026: '2026 வரை செல்லுபடியாகும்',
    manage_enterprise: 'நிறுவன சான்றுகள் & விவரங்களை நிர்வகிக்கவும்',
    ask_praman_badge: 'AI இணக்க உதவியாளர்',
    live_gazette_sync: 'நேரலை அரசிதழ் ஒத்திசைவு',
    ask_praman_title: 'பிரமாண் இணக்க உதவியாளரிடம் கேளுங்கள்',
    ask_praman_sub: 'இந்திய மொழிகளில் கேளுங்கள். அதிகாரப்பூர்வ BIS அரசிதழ்கள் மற்றும் QCO களில் இருந்து உடனடி தகவல்.',
    search_praman_placeholder: 'IS 4151, கட்டாய QCO அல்லது அருகிலுள்ள ஆய்வகம் பற்றி கேட்கவும்',
    quick_regulatory_services: 'விரைவு ஒழுங்குமுறை சேவைகள்',
    qco_checker_title: 'QCO மற்றும் தரநிலைகள் சரிபார்ப்பு',
    qco_checker_badge: 'கட்டாயமானது',
    qco_checker_sub: '14,000+ இந்திய தரநிலைகள் & அரசிதழ்களைத் தேடுங்கள்',
    doc_vault_title: 'ஆவண பெட்டகம்',
    doc_vault_badge: '3 சான்றுகள்',
    doc_vault_sub: '3 சரிபார்க்கப்பட்ட சான்றிதழ்கள் & NABL சோதனை அறிக்கைகள்',

    // Praman AI
    praman_header_title: 'பிரமாண் இணக்க உதவியாளர்',
    praman_header_sub: 'அதிகாரப்பூர்வ BIS ஒழுங்குமுறை அறிவுத்தளம்',
    auto_lang_banner: 'தானியங்கி மொழி கண்டறிதல் செயலில் உள்ளது · தமிழ், ஆங்கிலம், இந்தி, தெலுங்கு, கன்னடம், மலையாளம்...',
    praman_welcome: 'வணக்கம், நான் பிரமாண், உங்கள் இந்திய தர நிர்ணய பணியக இணக்க உதவியாளர். நீங்கள் தமிழ், ஆங்கிலம், இந்தி, தெலுங்கு, கன்னடம் அல்லது மலையாளத்தில் கேட்கலாம்.\n\nஒவ்வொரு பதிலும் அதிகாரப்பூர்வ BIS அரசிதழ்கள் மற்றும் NABL சோதனை நெறிமுறைகளில் இருந்து பெறப்படுகிறது.',
    ask_input_placeholder: 'தமிழில் கேட்கவும் அல்லது உள்ளிடவும்...',
    chat_sessions: 'அரட்டை அமர்வுகள்',
    new_chat: 'புதிய அரட்டை',
    pinned_chats: 'பின் செய்யப்பட்ட அரட்டைகள்',
    recent_chats: 'சமீபத்திய அரட்டைகள்',
    pin_chat: 'பின் செய்',
    unpin_chat: 'அன்பின் செய்',
    rename_chat: 'பெயர் மாற்று',
    delete_chat: 'நீக்கு',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    rename_chat_title: 'அரட்டை பெயரை மாற்றவும்',
    enter_new_title: 'புதிய பெயரை உள்ளிடவும்',
    no_chats_found: 'சேமிக்கப்பட்ட அரட்டைகள் இல்லை',

    // Standards
    standards_title: 'தரநிலைகள் மற்றும் QCO சரிபார்ப்பு',
    standards_sub: 'அதிகாரப்பூர்வ இந்திய தரநிலைகள் பணியகம் பதிவேடு மற்றும் QCO ஆணைகள்',
    verify_compliance_prompt: 'தயாரிப்பு இணக்கம் & கட்டாய தரநிலைகளை சரிபார்க்கவும்',
    standards_input_placeholder: 'எ.கா. ஹெல்மெட், IS 4151, பிளக்குகள்',
    run_qco_check_btn: 'QCO அறிவு வரைபட சோதனையை இயக்கவும்',
    jurisdiction_label: 'ஒழுங்குமுறை அதிகார வரம்பு மற்றும் அமலாக்க மண்டலம்',
    change_zone_btn: 'மண்டலத்தை மாற்று',
    jurisdiction_desc: 'இந்த அமைப்பு உங்கள் நியமிக்கப்பட்ட BIS கிளை அலுவலகத்தை அமைக்கிறது மற்றும் 250 கிமீக்குள் உள்ள NABL ஆய்வகங்களுக்கு முன்னுரிமை அளிக்கிறது.',
    division_councils_title: 'BIS தரநிலைகள் பிரிவு கவுன்சில்கள்',
    division_councils_sub: '8 மத்திய தொழில்நுட்ப பிரிவுகள் · 14,000+ இந்திய தரநிலைகள்',
    standards_count_suffix: 'தரநிலைகள்',

    // Services
    services_badge: 'அதிகாரப்பூர்வ BIS திட்டங்கள்',
    services_title: 'இந்திய தரநிலைகள் பணியக சேவைகள்',
    services_sub: 'தயாரிப்பு சான்றிதழ், தரநிலைக் கழகங்கள், தொழில்முறை NITS பயிற்சி மற்றும் நுகர்வோர் விவகாரங்களை ஆராயுங்கள்.',
    target_eligibility: 'இலக்கு தகுதி',
    open_scheme_portal: 'அதிகாரப்பூர்வ திட்ட போர்ட்டலைத் திறக்கவும்',

    // NABL Labs
    labs_title: 'அனைத்திந்திய பரிசோதனை ஆய்வகங்கள் அடைவு',
    labs_sub: 'இந்தியா முழுவதும் அதிகாரப்பூர்வ BIS அங்கீகாரம் பெற்ற மற்றும் NABL அங்கீகாரம் பெற்ற ஆய்வகங்கள்',
    current_facility_label: 'உங்கள் தற்போதைய பதிவு செய்யப்பட்ட வசதி',
    primary_facility_badge: 'முதன்மை வசதி',
    filter_region: 'பகுதி / மாநில வாரியாக வடிகட்டவும்',
    filter_scope: 'தயாரிப்பு சோதனை நோக்கம் மூலம் வடிகட்டவும்',
    showing_facilities: 'அங்கீகரிக்கப்பட்ட வசதிகள் காட்டப்படுகின்றன',
    near_you: 'உங்கள் அருகில்',
    proximity: 'அண்மை தூரம்',
    accredited_scope_label: 'அங்கீகரிக்கப்பட்ட சோதனை நோக்கம்',
    open_google_maps: 'கூகுள் மேப்ஸில் திறக்கவும்',

    // Settings
    settings_title: 'அமைப்புகள் & விருப்பத்தேர்வுகள்',
    app_language_title: 'பயன்பாட்டு மொழி & இடைமுகம்',
    app_language_sub: 'அனைத்து பக்கங்களிலும் இயல்புநிலை காட்சி மொழியை அமைக்கிறது.',
    notifications_title: 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    gazette_alerts: 'QCO அரசிதழ் கட்டாய எச்சரிக்கைகள்',
    gazette_alerts_sub: 'புதிய தரநிலைகள் வெளியிடப்படும் போது உடனடி எச்சரிக்கை',
    audit_reminders: 'கண்காணிப்பு தணிக்கை நினைவூட்டல்கள்',
    audit_reminders_sub: 'ஆய்வக சோதனை பதிவுகளுக்கான காலாண்டு நினைவூட்டல்கள்',
    back: 'பின்செல்',

    // Profile
    profile_title: 'நிறுவன சான்றுகள்',
    profile_sub: 'பிஐஎஸ் உரிமப் பதிவேடு மற்றும் இணக்கப் பதிவுகள்',
    tab_licenses: 'உரிமங்கள்',
    tab_audit: 'தணிக்கை & பார்வைகள்',
    tab_officer: 'பிஐஎஸ் அதிகாரி',
    audit_score: 'தணிக்கை மதிப்பெண்',
    active_licenses: 'செயலில் உள்ள உரிமங்கள்',
    next_surveillance: 'அடுத்த கண்காணிப்பு',
    factory_premises: 'தொழிற்சாலை வளாகம்',
    auth_signatory: 'அங்கீகரிக்கப்பட்ட கையொப்பமிட்டவர்',
    factory_unit: 'தொழிற்சாலை பிரிவு',
    lab_clearance: 'ஆய்வக அனுமதி',
    surveillance_visit: 'கண்காணிப்பு வருகை',
    view_license_cert: 'உரிமச் சான்றிதழைப் பார்க்கவும்',
    standard_specs: 'தரநிலை விவரக்குறிப்புகள்',
    next_audit_title: 'அடுத்த தணிக்கை: 18-Nov-2024',
    surveillance_desc: 'சிஎன்பிஓ (CNBO) திட்டமிட்ட இருசக்கர வாகன ஹெல்மெட்டுகளுக்கான (IS 4151) கண்காணிப்பு ஆய்வு. ஆவணப் பெட்டகத்தில் சோதனை பதிவுகளை பராமரிக்கவும்.',
    prepare_audit_docs: 'தணிக்கை ஆவணங்களைத் தயார் செய்யவும்',
    compliance_lifecycle: 'இணக்க வாழ்க்கைச் சுழற்சி',
    branch_office: 'கிளை அலுவலகம்',
    office_hours: 'அலுவலக நேரம்',
    email_branch: 'கிளைக்கு மின்னஞ்சல் அனுப்பவும்',

    // Ask Extra
    chip_prompt_helmet: 'இருசக்கர வாகன ஹெல்மெட் தரம் IS 4151',
    chip_prompt_bottle: 'துருப்பிடிக்காத எஃகு பாட்டில் IS 17803 சரிபார்க்கவும்',
    chip_prompt_labs: 'சென்னையில் உள்ள சோதனை ஆய்வகங்கள்',
    chip_prompt_fake_isi: 'போலி ISI முத்திரையை எவ்வாறு கண்டறிவது',
    chip_prompt_hallmark: 'தங்க ஹால்மார்க் மற்றும் HUID சரிபார்ப்பு',
    chip_prompt_complaint: 'நுகர்வோர் புகார் பதிவு 1800-11-4000',
    praman_disclaimer: 'உதவிக்கு மட்டுமே. BIS CARE அல்லது bis.gov.in இல் அதிகாரப்பூர்வமாக சரிபார்க்கவும்.',

    // Standards Extra
    resolved_classification: 'தீர்மானிக்கப்பட்ட வகைப்பாடு',
    applicable_standard: 'பொருந்தக்கூடிய தரம்',
    certification_scheme: 'சான்றிதழ் திட்டம்',
    enforcing_authority: 'அமலாக்க அதிகாரம் மற்றும் அரசிதழ்:',
    mandatory_testing_scope: 'கட்டாய சோதனை நோக்கம்:',
    open_bis_registry: 'அதிகாரப்பூர்வ பிஐஎஸ் தரநிலை பதிவேடு பக்கத்தைத் திறக்கவும்',
    related_standards: 'தொடர்புடைய மற்றும் குறுக்கு-குறிப்பு தரநிலைகள்',

    // Services Extra
    cat_all: 'அனைத்தும்',
    cat_industry: 'தொழில் மற்றும் உற்பத்தி',
    cat_youth: 'இளைஞர்கள் மற்றும் கல்வி',
    cat_capacity: 'திறன் மேம்பாடு',
    cat_testing: 'சோதனை மற்றும் அளவுத்திருத்தம்',
    cat_citizen: 'குடிமக்கள் சேவைகள்',
    cat_digital: 'டிஜிட்டல் சரிபார்ப்பு',

    // Vault
    vault_title: 'ஆவண பெட்டகம்',
    upload_doc_title: 'சான்றிதழ் அல்லது சோதனை அறிக்கையை பதிவேற்றவும்',
    upload_doc_sub: '15MB வரை PDF, JPG அல்லது PNG · உடனடி OCR பிரித்தெடுத்தல்',
    stored_certs: 'சேமிக்கப்பட்ட சான்றிதழ்கள்',

    // Dashboard Extra
    labs_dir_title: 'அனைத்திந்திய பரிசோதனை ஆய்வகங்கள் அடைவு',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'பொருள் மற்றும் நகரம் வாரியாக அங்கீகரிக்கப்பட்ட சோதனை வசதிகளைக் கண்டறியவும்',
    services_programmes_title: 'பிஐஎஸ் சேவைகள் & திட்டங்கள்',
    services_programmes_badge: 'திட்டங்கள்',
    services_programmes_sub: 'தரநிலைக் கழகங்கள், NITS பயிற்சி, LRS ஆய்வகத் திட்டம் & சான்றிதழ்',
    consumer_corner_title: 'நுகர்வோர் பாதுகாப்பு & குறைதீர்ப்பு மையம்',
    national_consumer_helpline: 'தேசிய நுகர்வோர் உதவி மையம்',
    toll_free: '1800-11-4000 (கட்டணமில்லா எண்)',
    call_now: 'இப்போதே அழைக்கவும்',
    consumer_card_desc: 'போலி ISI முத்திரைகள் அல்லது கட்டாய 6-இலக்க HUID குறியீடு இல்லாமல் விற்கப்படும் தங்க நகைகள் குறித்து நேரடியாக BIS அமலாக்கப் பிரிவிடம் புகார் செய்யவும்.',
    bis_grievance_portal: 'BIS குறைதீர்ப்பு போர்டல்',
    download_bis_care: 'BIS CARE செயலியைப் பதிவிறக்கவும்',
    chip_helmets: 'IS 4151 ஹெல்மெட்கள்',
    chip_gold: 'தங்க ஹால்மார்க் & HUID',
    chip_labs: 'NABL ஆய்வகங்களைக் கண்டறியவும்',
  },

  te: {
    // Tabs
    tab_dashboard: 'డ్యాష్‌బోర్డ్',
    tab_praman_ai: 'ప్రమాణ్ AI',
    tab_standards: 'ప్రమాణాలు',
    tab_services: 'సేవలు',
    tab_nabl_labs: 'NABL ల్యాబ్‌లు',
    tab_enterprise: 'ఎంటర్‌ప్రైజ్',

    // Dashboard
    greeting_title: 'శుభ సాయంత్రం, శ్రీపతి',
    greeting_sub: 'BIS లైసెన్సీ డ్యాష్‌బోర్డ్',
    enterprise_status: 'ఎంటర్‌ప్రైజ్ సమ్మతి స్థితి',
    qco_compliant: 'QCO కంప్లైంట్',
    registered_facility: 'నమోదిత కర్మాగారం',
    certified_product_lines: 'సర్టిఫైడ్ ఉత్పత్తులు · 2 క్రియాశీల ISI లైసెన్సులు',
    two_wheeler_helmets: 'టూ-వీలర్ హెల్మెట్‌లు',
    stainless_steel_flasks: 'స్టెయిన్‌లెస్ స్టీల్ ఫ్లాస్క్‌లు & వాటర్ బాటిల్స్',
    valid_2027: 'చెల్లుబాటు 2027',
    valid_2026: 'చెల్లుబాటు 2026',
    manage_enterprise: 'ఎంటర్‌ప్రైజ్ క్రెడెన్షియల్స్ నిర్వహించండి',
    ask_praman_badge: 'AI సమ్మతి సహాయకుడు',
    live_gazette_sync: 'లైవ్ గెజిట్ సమకాలీకరణ',
    ask_praman_title: 'ప్రమాణ్ సహాయకుడిని అడగండి',
    ask_praman_sub: 'భారతీయ భాషల్లో అడగండి. అధికారిక BIS గెజిట్లు, QCOల నుండి తక్షణ సమాచారం.',
    search_praman_placeholder: 'IS 4151, తప్పనిసరి QCO లేదా సమీప ల్యాబ్ గురించి అడగండి',
    quick_regulatory_services: 'త్వరిత నియంత్రణ సేవలు',
    qco_checker_title: 'QCO & ప్రమాణాల తనిఖీ',
    qco_checker_badge: 'తప్పనిసరి',
    qco_checker_sub: '14,000+ భారతీయ ప్రమాణాలు & గెజిట్లను శోధించండి',
    doc_vault_title: 'పత్రాల వాల్ట్',
    doc_vault_badge: '3 ఆధారాలు',
    doc_vault_sub: '3 ధృవీకరించబడిన సర్టిఫికెట్లు & NABL నివేదికలు',

    // Praman AI
    praman_header_title: 'ప్రమాణ్ సమ్మతి సహాయకుడు',
    praman_header_sub: 'అధికారిక BIS నాలెడ్జ్ బేస్',
    auto_lang_banner: 'ఆటో భాష గుర్తింపు సక్రియం · తెలుగు, ఇంగ్లీష్, హిందీ, తమిళం, కన్నడ...',
    praman_welcome: 'నమస్కారం, నేను ప్రమాణ్, మీ బ్యూరో ఆఫ్ ఇండియన్ స్టాండర్డ్స్ సలహాదారుని. మీరు తెలుగు, ఇంగ్లీష్, హిందీ మొదలైన భాషలలో అడగవచ్చు.',
    ask_input_placeholder: 'తెలుగు లేదా ఇంగ్లీషులో అడగండి...',
    chat_sessions: 'చాట్ సెషన్లు',
    new_chat: 'కొత్త చాట్',
    pinned_chats: 'పిన్ చేసిన చాట్‌లు',
    recent_chats: 'ఇటీవలి చాట్‌లు',
    pin_chat: 'పిన్ చేయి',
    unpin_chat: 'అన్‌పిన్ చేయి',
    rename_chat: 'పేరు మార్చు',
    delete_chat: 'తొలగించు',
    save: 'సేవ్ చేయి',
    cancel: 'రద్దు చేయి',
    rename_chat_title: 'చాట్ పేరు మార్చండి',
    enter_new_title: 'కొత్త శీర్షికను నమోదు చేయండి',
    no_chats_found: 'చాట్‌లు లేవు',

    // Standards
    standards_title: 'ప్రమాణాలు మరియు QCO ధృవీకరణ',
    standards_sub: 'అధికారిక భారతీయ ప్రమాణాల బ్యూరో రిజిస్ట్రీ',
    verify_compliance_prompt: 'ఉత్పత్తి సమ్మతి మరియు తప్పనిసరి ప్రమాణాలను ధృవీకరించండి',
    standards_input_placeholder: 'ఉదా. హెల్మెట్, IS 4151, ప్లగ్‌లు',
    run_qco_check_btn: 'QCO నాలెడ్జ్ గ్రాఫ్ తనిఖీని అమలు చేయండి',
    jurisdiction_label: 'నియంత్రణ అధికార పరిధి మరియు జోన్',
    change_zone_btn: 'జోన్ మార్చండి',
    jurisdiction_desc: 'ఈ సెట్టింగ్ మీ సమీప BIS కార్యాలయాన్ని మరియు 250 కి.మీ పరిధిలోని NABL ల్యాబ్‌లను ప్రాధాన్యతనిస్తుంది.',
    division_councils_title: 'BIS ప్రమాణాల విభాగ కౌన్సిల్‌లు',
    division_councils_sub: '8 సాంకేతిక విభాగాలు · 14,000+ భారతీయ ప్రమాణాలు',
    standards_count_suffix: 'ప్రమాణాలు',

    // Services
    services_badge: 'అధికారిక BIS పథకాలు',
    services_title: 'భారతీయ ప్రమాణాల బ్యూరో సేవలు',
    services_sub: 'ఉత్పత్తి ధృవీకరణ, శిక్షణ మరియు వినియోగదారు వ్యవహారాల కార్యక్రమాలు.',
    target_eligibility: 'అర్హత',
    open_scheme_portal: 'అధికారిక పోర్టల్ తెరవండి',

    // NABL Labs
    labs_title: 'అఖిల భారత పరీక్షా ప్రయోగశాలల డైరెక్టరీ',
    labs_sub: 'భారతదేశం అంతటా అధికారిక BIS-గుర్తింపు పొందిన & NABL ల్యాబ్‌లు',
    current_facility_label: 'మీ ప్రస్తుత నమోదిత సదుపాయం',
    primary_facility_badge: 'ప్రాథమిక సదుపాయం',
    filter_region: 'ప్రాంతం / రాష్ట్రం వారీగా ఫిల్టర్ చేయండి',
    filter_scope: 'ఉత్పత్తి పరిధి వారీగా ఫిల్టర్ చేయండి',
    showing_facilities: 'అక్రిడిటెడ్ ల్యాబ్‌లు ప్రదర్శించబడుతున్నాయి',
    near_you: 'మీ సమీపంలో',
    proximity: 'సమీప దూరం',
    accredited_scope_label: 'గుర్తింపు పొందిన పరీక్షా పరిధి',
    open_google_maps: 'గూగుల్ మ్యాప్స్‌లో తెరవండి',

    // Settings
    settings_title: 'సెట్టింగ్‌లు & ప్రాధాన్యతలు',
    app_language_title: 'యాప్ భాష & ఇంటర్‌ఫేస్',
    app_language_sub: 'అన్ని పేజీలలో డిఫాల్ట్ ప్రదర్శన భాషను సెట్ చేస్తుంది.',
    notifications_title: 'నోటిఫికేషన్ ప్రాధాన్యతలు',
    gazette_alerts: 'QCO గెజిట్ హెచ్చరికలు',
    gazette_alerts_sub: 'కొత్త ప్రమాణాలు విడుదలైనప్పుడు తక్షణ అలర్ట్',
    audit_reminders: 'ఆడిట్ రిమైండర్‌లు',
    audit_reminders_sub: 'త్రైమాసిక టెస్ట్ రికార్డుల రిమైండర్‌లు',
    back: 'వెనుకకు',

    // Profile
    profile_title: 'ఎంటర్‌ప్రైజ్ ఆధారాలు',
    profile_sub: 'BIS లైసెన్స్ రిజిస్ట్రీ మరియు సమ్మతి రికార్డులు',
    tab_licenses: 'లైసెన్సులు',
    tab_audit: 'ఆడిట్ & సందర్శనలు',
    tab_officer: 'BIS అధికారి',
    audit_score: 'ఆడిట్ స్కోరు',
    active_licenses: 'క్రియాశీల లైసెన్సులు',
    next_surveillance: 'తదుపరి నిఘా',
    factory_premises: 'ఫ్యాక్టరీ ప్రాంగణం',
    auth_signatory: 'అధికారిక సంతకందారు',
    factory_unit: 'ఫ్యాక్టరీ యూనిట్',
    lab_clearance: 'ల్యాబ్ క్లియరెన్స్',
    surveillance_visit: 'నిఘా సందర్శన',
    view_license_cert: 'లైసెన్స్ సర్టిఫికేట్ చూడండి',
    standard_specs: 'ప్రామాణిక లక్షణాలు',
    next_audit_title: 'తదుపరి ఆడిట్: 18-Nov-2024',
    surveillance_desc: 'ద్విచక్ర వాహన హెల్మెట్‌ల (IS 4151) నిఘా తనిఖీ. డాక్యుమెంట్ వాల్ట్‌లో టెస్ట్ రికార్డులను నిర్వహించండి.',
    prepare_audit_docs: 'ఆడిట్ పత్రాలను సిద్ధం చేయండి',
    compliance_lifecycle: 'సమ్మతి జీవితచక్రం',
    branch_office: 'బ్రాంచ్ కార్యాలయం',
    office_hours: 'కార్యాలయ వేళలు',
    email_branch: 'బ్రాంచ్‌కి ఈమెయిల్ చేయండి',

    // Ask Extra
    chip_prompt_helmet: 'ద్విచక్ర వాహన హెల్మెట్ ప్రమాణం IS 4151',
    chip_prompt_bottle: 'స్టెయిన్‌లెస్ స్టీల్ బాటిల్ IS 17803 ధృవీకరించండి',
    chip_prompt_labs: 'చెన్నైలోని టెస్టింగ్ ల్యాబ్‌లు',
    chip_prompt_fake_isi: 'నకిలీ ISI మార్కును ఎలా గుర్తించాలి',
    chip_prompt_hallmark: 'బంగారు హాల్‌మార్క్ మరియు HUID ధృవీకరణ',
    chip_prompt_complaint: 'వినియోగదారుల ఫిర్యాదు నమోదు 1800-11-4000',
    praman_disclaimer: 'సహాయార్థం మాత్రమే. BIS CARE లేదా bis.gov.in లో అధికారికంగా ధృవీకరించండి.',

    // Standards Extra
    resolved_classification: 'పరిష్కరించబడిన వర్గీకరణ',
    applicable_standard: 'వర్తించే ప్రమాణం',
    certification_scheme: 'ధృవీకరణ పథకం',
    enforcing_authority: 'అమలు చేసే అధికారం మరియు గెజిట్:',
    mandatory_testing_scope: 'తప్పనిసరి పరీక్ష పరిధి:',
    open_bis_registry: 'అధికారిక BIS రిజిస్ట్రీ పేజీని తెరవండి',
    related_standards: 'సంబంధిత ప్రమాణాలు',

    // Services Extra
    cat_all: 'అన్నీ',
    cat_industry: 'పరిశ్రమ మరియు తయారీ',
    cat_youth: 'యువత మరియు విద్య',
    cat_capacity: 'సామర్థ్య పెంపుదల',
    cat_testing: 'పరీక్ష మరియు క్రమాంకనం',
    cat_citizen: 'పౌర సేవలు',
    cat_digital: 'డిజిటల్ ధృవీకరణ',

    // Vault
    vault_title: 'డాక్యుమెంట్ వాల్ట్',
    upload_doc_title: 'సర్టిఫికేట్ లేదా పరీక్ష నివేదికను అప్‌లోడ్ చేయండి',
    upload_doc_sub: '15MB వరకు PDF, JPG లేదా PNG · తక్షణ OCR గుర్తింపు',
    stored_certs: 'నిల్వ చేయబడిన సర్టిఫికెట్లు',

    // Dashboard Extra
    labs_dir_title: 'అఖిల భారత పరీక్షా ప్రయోగశాలల డైరెక్టరీ',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'ఉత్పత్తి మరియు నగరం వారీగా గుర్తింపు పొందిన ల్యాబ్‌లను కనుగొనండి',
    services_programmes_title: 'BIS సేవలు & పథకాలు',
    services_programmes_badge: 'పథకాలు',
    services_programmes_sub: 'స్టాండర్డ్స్ క్లబ్‌లు, NITS శిక్షణ, LRS ల్యాబ్ పథకం & ధృవీకరణ',
    consumer_corner_title: 'వినియోగదారుల రక్షణ & పరిష్కార వేదిక',
    national_consumer_helpline: 'జాతీయ వినియోగదారుల హెల్ప్‌లైన్',
    toll_free: '1800-11-4000 (టోల్-ఫ్రీ)',
    call_now: 'ఇప్పుడే కాల్ చేయండి',
    consumer_card_desc: 'నకిలీ ISI మార్కులు లేదా తప్పనిసరి 6-అంకెల HUID కోడ్ లేకుండా విక్రయించే బంగారు ఆభరణాలపై నేరుగా BIS కి ఫిర్యాదు చేయండి.',
    bis_grievance_portal: 'BIS ఫిర్యాదుల పోర్టల్',
    download_bis_care: 'BIS CARE యాప్‌ను డౌన్‌లోడ్ చేయండి',
    chip_helmets: 'IS 4151 హెల్మెట్లు',
    chip_gold: 'బంగారు హాల్‌మార్క్ & HUID',
    chip_labs: 'NABL ల్యాబ్‌లను కనుగొనండి',
  },

  kn: {
    // Tabs
    tab_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    tab_praman_ai: 'ಪ್ರಮಾಣ್ AI',
    tab_standards: 'ಮಾನದಂಡಗಳು',
    tab_services: 'ಸೇವೆಗಳು',
    tab_nabl_labs: 'NABL ಲ್ಯಾಬ್‌ಗಳು',
    tab_enterprise: 'ಉದ್ಯಮ',

    // Dashboard
    greeting_title: 'ಶುಭ ಸಂಜೆ, ಶ್ರೀಪತಿ',
    greeting_sub: 'BIS ಪರವಾನಗಿದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    enterprise_status: 'ಉದ್ಯಮ ಅನುಸರಣೆ ಸ್ಥಿತಿ',
    qco_compliant: 'QCO ಅನುಸರಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
    registered_facility: 'ನೋಂದಾಯಿತ ಸೌಲಭ್ಯ',
    certified_product_lines: 'ಪ್ರಮಾಣೀಕೃತ ಉತ್ಪನ್ನಗಳು · 2 ಸಕ್ರಿಯ ISI ಪರವಾನಗಿಗಳು',
    two_wheeler_helmets: 'ದ್ವಿಚಕ್ರ ವಾಹನ ಹೆಲ್ಮೆಟ್‌ಗಳು',
    stainless_steel_flasks: 'ಸ್ಟೇನ್‌ಲೆಸ್ ಸ್ಟೀಲ್ ಫ್ಲಾಸ್ಕ್‌ಗಳು ಮತ್ತು ಬಾಟಲಿಗಳು',
    valid_2027: 'ಮಾನ್ಯತೆ 2027',
    valid_2026: 'ಮಾನ್ಯತೆ 2026',
    manage_enterprise: 'ಉದ್ಯಮ ರುಜುವಾತುಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    ask_praman_badge: 'AI ಅನುಸರಣೆ ಸಹಾಯಕ',
    live_gazette_sync: 'ಲೈವ್ ಗೆಜೆಟ್ ಸಿಂಕ್',
    ask_praman_title: 'ಪ್ರಮಾಣ್ ಸಹಾಯಕನನ್ನು ಕೇಳಿ',
    ask_praman_sub: 'ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಕೇಳಿ. ಅಧಿಕೃತ BIS ಗೆಜೆಟ್‌ಗಳು ಮತ್ತು QCO ಗಳಿಂದ ತ್ವರಿತ ಮಾಹಿತಿ.',
    search_praman_placeholder: 'IS 4151, ಕಡ್ಡಾಯ QCO ಅಥವಾ ಹತ್ತಿರದ ಲ್ಯಾಬ್ ಬಗ್ಗೆ ಕೇಳಿ',
    quick_regulatory_services: 'ತ್ವರಿತ ನಿಯಂತ್ರಕ ಸೇವೆಗಳು',
    qco_checker_title: 'QCO ಮತ್ತು ಮಾನದಂಡಗಳ ಪರೀಕ್ಷಕ',
    qco_checker_badge: 'ಕಡ್ಡಾಯ',
    qco_checker_sub: '14,000+ ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು ಹುಡುಕಿ',
    doc_vault_title: 'ದಾಖಲೆ ವಾಲ್ಟ್',
    doc_vault_badge: '3 ರುಜುವಾತುಗಳು',
    doc_vault_sub: '3 ಪರಿಶೀಲಿಸಿದ ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು NABL ವರದಿಗಳು',

    // Praman AI
    praman_header_title: 'ಪ್ರಮಾಣ್ ಅನುಸರಣೆ ಸಹಾಯಕ',
    praman_header_sub: 'ಅಧಿಕೃತ BIS ಜ್ಞಾನ ಭಂಡಾರ',
    auto_lang_banner: 'ಸ್ವಯಂ ಭಾಷೆ ಪತ್ತೆ ಸಕ್ರಿಯ · ಕನ್ನಡ, ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ, ತಮಿಳು, ತೆಲುಗು...',
    praman_welcome: 'ನಮಸ್ಕಾರ, ನಾನು ಪ್ರಮಾಣ್, ನಿಮ್ಮ ಬ್ಯೂರೋ ಆಫ್ ಇಂಡಿಯನ್ ಸ್ಟ್ಯಾಂಡರ್ಡ್ಸ್ ಸಹಾಯಕ. ನೀವು ಕನ್ನಡ, ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ ಭಾಷೆಗಳಲ್ಲಿ ಕೇಳಬಹುದು.',
    ask_input_placeholder: 'ಕನ್ನಡದಲ್ಲಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಕೇಳಿ...',
    chat_sessions: 'ಚಾಟ್ ಅವಧಿಗಳು',
    new_chat: 'ಹೊಸ ಚಾಟ್',
    pinned_chats: 'ಪಿನ್ ಮಾಡಿದ ಚಾಟ್‌ಗಳು',
    recent_chats: 'ಇತ್ತೀಚಿನ ಚಾಟ್‌ಗಳು',
    pin_chat: 'ಪಿನ್ ಮಾಡಿ',
    unpin_chat: 'ಅನ್‌ಪಿನ್ ಮಾಡಿ',
    rename_chat: 'ಮರುಹೆಸರಿಸಿ',
    delete_chat: 'ಅಳಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    rename_chat_title: 'ಚಾಟ್ ಶೀರ್ಷಿಕೆ ಬದಲಾಯಿಸಿ',
    enter_new_title: 'ಹೊಸ ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ',
    no_chats_found: 'ಯಾವುದೇ ಚಾಟ್ ಲಭ್ಯವಿಲ್ಲ',

    // Standards
    standards_title: 'ಮಾನದಂಡಗಳು ಮತ್ತು QCO ಪರಿಶೀಲನೆ',
    standards_sub: 'ಅಧಿಕೃತ ಭಾರತೀಯ ಮಾನದಂಡಗಳ ಬ್ಯೂರೋ ನೋಂದಣಿ',
    verify_compliance_prompt: 'ಉತ್ಪನ್ನ ಅನುಸರಣೆ ಮತ್ತು ಕಡ್ಡಾಯ ಮಾನದಂಡಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    standards_input_placeholder: 'ಉದಾ. ಹೆಲ್ಮೆಟ್, IS 4151, ಪ್ಲಗ್‌ಗಳು',
    run_qco_check_btn: 'QCO ಜ್ಞಾನ ಗ್ರಾಫ್ ಪರೀಕ್ಷೆ ಚಲಾಯಿಸಿ',
    jurisdiction_label: 'ನಿಯಂತ್ರಕ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿ',
    change_zone_btn: 'ವಲಯ ಬದಲಾಯಿಸಿ',
    jurisdiction_desc: 'ಈ ಸೆಟ್ಟಿಂಗ್ ನಿಮ್ಮ ನಿಯೋಜಿತ BIS ಕಚೇರಿ ಮತ್ತು 250 ಕಿ.ಮೀ ವ್ಯಾಪ್ತಿಯ NABL ಲ್ಯಾಬ್‌ಗಳನ್ನು ಆದ್ಯತೆ ಮಾಡುತ್ತದೆ.',
    division_councils_title: 'BIS ಮಾನದಂಡಗಳ ವಿಭಾಗ ಕೌನ್ಸಿಲ್‌ಗಳು',
    division_councils_sub: '8 ತಾಂತ್ರಿಕ ವಿಭಾಗಗಳು · 14,000+ ಭಾರತೀಯ ಮಾನದಂಡಗಳು',
    standards_count_suffix: 'ಮಾನದಂಡಗಳು',

    // Services
    services_badge: 'ಅಧಿಕೃತ BIS ಯೋಜನೆಗಳು',
    services_title: 'ಭಾರತೀಯ ಮಾನದಂಡಗಳ ಬ್ಯೂರೋ ಸೇವೆಗಳು',
    services_sub: 'ಉತ್ಪನ್ನ ಪ್ರಮಾಣೀಕರಣ, ತರಬೇತಿ ಮತ್ತು ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳ ಉಪಕ್ರಮಗಳು.',
    target_eligibility: 'ಅರ್ಹತೆ',
    open_scheme_portal: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ',

    // NABL Labs
    labs_title: 'ಅಖಿಲ ಭಾರತ ಪರೀಕ್ಷಾ ಪ್ರಯೋಗಾಲಯಗಳ ಡೈರೆಕ್ಟರಿ',
    labs_sub: 'ಭಾರತದಾದ್ಯಂತ ಅಧಿಕೃತ BIS-ಮಾನ್ಯತೆ ಪಡೆದ NABL ಲ್ಯಾಬ್‌ಗಳು',
    current_facility_label: 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ನೋಂದಾಯಿತ ಸೌಲಭ್ಯ',
    primary_facility_badge: 'ಪ್ರಾಥಮಿಕ ಸೌಲಭ್ಯ',
    filter_region: 'ಪ್ರದೇಶ / ರಾಜ್ಯವಾರು ಫಿಲ್ಟರ್ ಮಾಡಿ',
    filter_scope: 'ಉತ್ಪನ್ನ ಪರೀಕ್ಷಾ ವ್ಯಾಪ್ತಿಯ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ',
    showing_facilities: 'ಮಾನ್ಯತೆ ಪಡೆದ ಸೌಲಭ್ಯಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    near_you: 'ನಿಮ್ಮ ಹತ್ತಿರ',
    proximity: 'ದೂರ',
    accredited_scope_label: 'ಮಾನ್ಯತೆ ಪಡೆದ ಪರೀಕ್ಷಾ ವ್ಯಾಪ್ತಿ',
    open_google_maps: 'ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',

    // Settings
    settings_title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು',
    app_language_title: 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ ಮತ್ತು ಇಂಟರ್ಫೇಸ್',
    app_language_sub: 'ಎಲ್ಲಾ ಪುಟಗಳಲ್ಲಿ ಡೀಫಾಲ್ಟ್ ಭಾಷೆಯನ್ನು ಹೊಂದಿಸುತ್ತದೆ.',
    notifications_title: 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    gazette_alerts: 'QCO ಗೆಜೆಟ್ ಎಚ್ಚರಿಕೆಗಳು',
    gazette_alerts_sub: 'ಹೊಸ ಮಾನದಂಡಗಳ ತ್ವರಿತ ಪುಶ್ ಎಚ್ಚರಿಕೆ',
    audit_reminders: 'ಆಡಿಟ್ ಜ್ಞಾಪನೆಗಳು',
    audit_reminders_sub: 'ತ್ರೈಮಾಸಿಕ ಪರೀಕ್ಷಾ ದಾಖಲೆಗಳ ಜ್ಞಾಪನೆಗಳು',
    back: 'ಹಿಂದೆ',

    // Profile
    profile_title: 'ಉದ್ಯಮ ರುಜುವಾತುಗಳು',
    profile_sub: 'ಬಿಐಎಸ್ ಪರವಾನಗಿ ನೋಂದಣಿ ಮತ್ತು ಅನುಸರಣಾ ದಾಖಲೆಗಳು',
    tab_licenses: 'ಪರವಾನಗಿಗಳು',
    tab_audit: 'ಆಡಿಟ್ ಮತ್ತು ಭೇಟಿಗಳು',
    tab_officer: 'ಬಿಐಎಸ್ ಅಧಿಕಾರಿ',
    audit_score: 'ಆಡಿಟ್ ಸ್ಕೋರ್',
    active_licenses: 'ಸಕ್ರಿಯ ಪರವಾನಗಿಗಳು',
    next_surveillance: 'ಮುಂದಿನ ಕಣ್ಗಾವಲು',
    factory_premises: 'ಕಾರ್ಖಾನೆ ಆವರಣ',
    auth_signatory: 'ಅಧಿಕೃತ ಸಹಿದಾರರು',
    factory_unit: 'ಕಾರ್ಖಾನೆ ಘಟಕ',
    lab_clearance: 'ಪ್ರಯೋಗಾಲಯ ಅನುಮತಿ',
    surveillance_visit: 'ಕಣ್ಗಾವಲು ಭೇಟಿ',
    view_license_cert: 'ಪರವಾನಗಿ ಪ್ರಮಾಣಪತ್ರ ನೋಡಿ',
    standard_specs: 'ಮಾನದಂಡ ವಿವರಣೆಗಳು',
    next_audit_title: 'ಮುಂದಿನ ಆಡಿಟ್: 18-Nov-2024',
    surveillance_desc: 'ದ್ವಿಚಕ್ರ ವಾಹನ ಹೆಲ್ಮೆಟ್‌ಗಳ (IS 4151) ಕಣ್ಗಾವಲು ತಪಾಸಣೆ. ಡಾಕ್ಯುಮೆಂಟ್ ವಾಲ್ಟ್‌ನಲ್ಲಿ ಪರೀಕ್ಷಾ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    prepare_audit_docs: 'ಆಡಿಟ್ ದಾಖಲೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಿ',
    compliance_lifecycle: 'ಅನುಸರಣೆ ಜೀವನಚಕ್ರ',
    branch_office: 'ಶಾಖಾ ಕಚೇರಿ',
    office_hours: 'ಕಚೇರಿ ಸಮಯ',
    email_branch: 'ಶಾಖೆಗೆ ಇಮೇಲ್ ಮಾಡಿ',

    // Ask Extra
    chip_prompt_helmet: 'ದ್ವಿಚಕ್ರ ವಾಹನ ಹೆಲ್ಮೆಟ್ ಮಾನದಂಡ IS 4151',
    chip_prompt_bottle: 'ಸ್ಟೇನ್ಲೆಸ್ ಸ್ಟೀಲ್ ಬಾಟಲ್ IS 17803 ಪರಿಶೀಲಿಸಿ',
    chip_prompt_labs: 'ಚೆನ್ನೈನಲ್ಲಿರುವ ಪರೀಕ್ಷಾ ಲ್ಯಾಬ್‌ಗಳು',
    chip_prompt_fake_isi: 'ನಕಲಿ ISI ಮಾರ್ಕ್ ಅನ್ನು ಹೇಗೆ ಪರೀಕ್ಷಿಸುವುದು',
    chip_prompt_hallmark: 'ಚಿನ್ನದ ಹಾಲ್‌ಮಾರ್ಕ್ ಮತ್ತು HUID ಪರಿಶೀಲನೆ',
    chip_prompt_complaint: 'ಗ್ರಾಹಕ ದೂರು ದಾಖಲಿಸಿ 1800-11-4000',
    praman_disclaimer: 'ಕೇವಲ ಸಹಾಯಕ್ಕಾಗಿ. BIS CARE ಅಥವಾ bis.gov.in ನಲ್ಲಿ ಅಧಿಕೃತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',

    // Standards Extra
    resolved_classification: 'ಪರಿಹರಿಸಲಾದ ವರ್ಗೀಕರಣ',
    applicable_standard: 'ಅನ್ವಯವಾಗುವ ಮಾನದಂಡ',
    certification_scheme: 'ಪ್ರಮಾಣೀಕರಣ ಯೋಜನೆ',
    enforcing_authority: 'ಜಾರಿ ಪ್ರಾಧಿಕಾರ ಮತ್ತು ಗೆಜೆಟ್:',
    mandatory_testing_scope: 'ಕಡ್ಡಾಯ ಪರೀಕ್ಷಾ ವ್ಯಾಪ್ತಿ:',
    open_bis_registry: 'ಅಧಿಕೃತ BIS ನೋಂದಣಿ ಪುಟವನ್ನು ತೆರೆಯಿರಿ',
    related_standards: 'ಸಂಬಂಧಿತ ಮಾನದಂಡಗಳು',

    // Services Extra
    cat_all: 'ಎಲ್ಲಾ',
    cat_industry: 'ಉದ್ಯಮ ಮತ್ತು ಉತ್ಪಾದನೆ',
    cat_youth: 'ಯುವಜನತೆ ಮತ್ತು ಶಿಕ್ಷಣ',
    cat_capacity: 'ಸಾಮರ್ಥ್ಯ ವೃದ್ಧಿ',
    cat_testing: 'ಪರೀಕ್ಷೆ ಮತ್ತು ಮಾಪನಾಂಕ ನಿರ್ಣಯ',
    cat_citizen: 'ನಾಗರಿಕ ಸೇವೆಗಳು',
    cat_digital: 'ಡಿಜಿಟಲ್ ಪರಿಶೀಲನೆ',

    // Vault
    vault_title: 'ದಾಖಲೆ ವಾಲ್ಟ್',
    upload_doc_title: 'ಪ್ರಮಾಣಪತ್ರ ಅಥವಾ ಪರೀಕ್ಷಾ ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    upload_doc_sub: '15MB ವರೆಗೆ PDF, JPG ಅಥವಾ PNG · ತ್ವರಿತ OCR ಎಕ್ಸ್‌ಟ್ರಾಕ್ಷನ್',
    stored_certs: 'ಸಂಗ್ರಹಿಸಲಾದ ಪ್ರಮಾಣಪತ್ರಗಳು',

    // Dashboard Extra
    labs_dir_title: 'ಅಖಿಲ ಭಾರತ ಪರೀಕ್ಷಾ ಪ್ರಯೋಗಾಲಯಗಳ ಡೈರೆಕ್ಟರಿ',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'ಉತ್ಪನ್ನ ಮತ್ತು ನಗರವಾರು ಮಾನ್ಯತೆ ಪಡೆದ ಪರೀಕ್ಷಾ ಸೌಲಭ್ಯಗಳನ್ನು ಹುಡುಕಿ',
    services_programmes_title: 'BIS ಸೇವೆಗಳು ಮತ್ತು ಯೋಜನೆಗಳು',
    services_programmes_badge: 'ಯೋಜನೆಗಳು',
    services_programmes_sub: 'ಸ್ಟ್ಯಾಂಡರ್ಡ್ಸ್ ಕ್ಲಬ್‌ಗಳು, NITS ತರಬೇತಿ, LRS ಲ್ಯಾಬ್ ಯೋಜನೆ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ',
    consumer_corner_title: 'ಗ್ರಾಹಕ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಕುಂದುಕೊರತೆ ವೇದಿಕೆ',
    national_consumer_helpline: 'ರಾಷ್ಟ್ರೀಯ ಗ್ರಾಹಕ ಸಹಾಯವಾಣಿ',
    toll_free: '1800-11-4000 (ಟೋಲ್-ಫ್ರೀ)',
    call_now: 'ಈಗ ಕರೆ ಮಾಡಿ',
    consumer_card_desc: 'ನಕಲಿ ISI ಮಾರ್ಕ್ ಅಥವಾ ಕಡ್ಡಾಯ 6-ಅಂಕಿಯ HUID ಕೋಡ್ ಇಲ್ಲದೆ ಮಾರಾಟವಾಗುವ ಚಿನ್ನದ ಆಭರಣಗಳ ಬಗ್ಗೆ ನೇರವಾಗಿ BIS ಗೆ ದೂರು ನೀಡಿ.',
    bis_grievance_portal: 'BIS ಕುಂದುಕೊರತೆ ಪೋರ್ಟಲ್',
    download_bis_care: 'BIS CARE ಅಪ್ಲಿಕೇಶನ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    chip_helmets: 'IS 4151 ಹೆಲ್ಮೆಟ್‌ಗಳು',
    chip_gold: 'ಚಿನ್ನದ ಹಾಲ್‌ಮಾರ್ಕ್ & HUID',
    chip_labs: 'NABL ಲ್ಯಾಬ್‌ಗಳನ್ನು ಹುಡುಕಿ',
  },

  ml: {
    // Tabs
    tab_dashboard: 'ഡാഷ്‌ബോർഡ്',
    tab_praman_ai: 'പ്രമാൺ AI',
    tab_standards: 'മാനദണ്ഡങ്ങൾ',
    tab_services: 'സേവനങ്ങൾ',
    tab_nabl_labs: 'NABL ലാബുകൾ',
    tab_enterprise: 'എന്റർപ്രൈസ്',

    // Dashboard
    greeting_title: 'ശുഭ സായാഹ്നം, ശ്രീപതി',
    greeting_sub: 'BIS ലൈസൻസി ഡാഷ്‌ബോർഡ്',
    enterprise_status: 'എന്റർപ്രൈസ് പാലിക്കൽ നില',
    qco_compliant: 'QCO പാലിച്ചു',
    registered_facility: 'രജിസ്റ്റർ ചെയ്ത സ്ഥാപനം',
    certified_product_lines: 'സർട്ടിഫൈഡ് ഉൽപ്പന്നങ്ങൾ · 2 സജീവ ISI ലൈസൻസുകൾ',
    two_wheeler_helmets: 'ഇരുചക്ര വാഹന ഹെൽമെറ്റുകൾ',
    stainless_steel_flasks: 'സ്റ്റെയിൻലെസ്സ് സ്റ്റീൽ ഫ്ലാസ്കുകൾ & കുപ്പികൾ',
    valid_2027: 'കാലാവധി 2027',
    valid_2026: 'കാലാവധി 2026',
    manage_enterprise: 'വിവരങ്ങൾ കൈകാര്യം ചെയ്യുക',
    ask_praman_badge: 'AI കംപ്ലയൻസ് അസിസ്റ്റന്റ്',
    live_gazette_sync: 'തത്സമയ ഗസറ്റ് സിങ്ക്',
    ask_praman_title: 'പ്രമാൺ അസിസ്റ്റന്റിനോട് ചോദിക്കുക',
    ask_praman_sub: 'ഭാരതീയ ഭാഷകളിൽ ചോദിക്കുക. ഔദ്യോഗിക BIS ഗസറ്റുകളിൽ നിന്നും തത്സമയ വിവരങ്ങൾ.',
    search_praman_placeholder: 'IS 4151, നിർബന്ധിത QCO അല്ലെങ്കിൽ സമീപത്തെ ലാബിനെക്കുറിച്ച് ചോദിക്കുക',
    quick_regulatory_services: 'റെഗുലേറ്ററി സേവനങ്ങൾ',
    qco_checker_title: 'QCO മാനദണ്ഡ പരിശോധന',
    qco_checker_badge: 'നിർബന്ധിതം',
    qco_checker_sub: '14,000+ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ തിരയുക',
    doc_vault_title: 'ഡോക്യുമെന്റ് വോൾട്ട്',
    doc_vault_badge: '3 സർട്ടിഫിക്കറ്റുകൾ',
    doc_vault_sub: '3 പരിശോധിച്ചുറപ്പിച്ച NABL റിപ്പോർട്ടുകൾ',

    // Praman AI
    praman_header_title: 'പ്രമാൺ കംപ്ലയൻസ് അസിസ്റ്റന്റ്',
    praman_header_sub: 'ഔദ്യോഗിക BIS വിവര ശേഖരം',
    auto_lang_banner: 'ഭാഷ കണ്ടെത്തൽ സജീവം · മലയാളം, ഇംഗ്ലീഷ്, ഹിന്ദി, തമിഴ്, തെലുങ്ക്...',
    praman_welcome: 'നമസ്കാരം, ഞാൻ പ്രമാൺ, ബ്യൂറോ ഓഫ് ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് അസിസ്റ്റന്റ്. നിങ്ങൾക്ക് മലയാളത്തിലോ ഇംഗ്ലീഷിലോ ചോദിക്കാം.',
    ask_input_placeholder: 'മലയാളത്തിലോ ഇംഗ്ലീഷിലോ ചോദിക്കുക...',
    chat_sessions: 'ചാറ്റ് സെഷനുകൾ',
    new_chat: 'പുതിയ ചാറ്റ്',
    pinned_chats: 'പിൻ ചെയ്ത ചാറ്റുകൾ',
    recent_chats: 'സമീപകാല ചാറ്റുകൾ',
    pin_chat: 'പിൻ ചെയ്യുക',
    unpin_chat: 'അൺപിൻ ചെയ്യുക',
    rename_chat: 'പേര് മാറ്റുക',
    delete_chat: 'ഡിലീറ്റ് ചെയ്യുക',
    save: 'സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    rename_chat_title: 'ചാറ്റിന്റെ പേര് മാറ്റുക',
    enter_new_title: 'പുതിയ പേര് നൽകുക',
    no_chats_found: 'ചാറ്റുകൾ ലഭ്യമല്ല',

    // Standards
    standards_title: 'മാനദണ്ഡങ്ങളും QCO പരിശോധനയും',
    standards_sub: 'ഔദ്യോഗിക ബ്യൂറോ ഓഫ് ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് രജിസ്ട്രി',
    verify_compliance_prompt: 'ഉൽപ്പന്ന മാനദണ്ഡങ്ങൾ പരിശോധിക്കുക',
    standards_input_placeholder: 'ഉദാ. ഹെൽമെറ്റ്, IS 4151, പ്ലഗ്ഗുകൾ',
    run_qco_check_btn: 'QCO ഗ്രാഫ് പരിശോധന നടത്തുക',
    jurisdiction_label: 'റെഗുലേറ്ററി അധികാരപരിധി',
    change_zone_btn: 'മേഖല മാറ്റുക',
    jurisdiction_desc: 'നിങ്ങളുടെ BIS ശാഖാ കാര്യാലയവും 250 കിലോമീറ്ററിനുള്ളിലെ NABL ലാബുകളും കണ്ടെത്തുന്നു.',
    division_councils_title: 'BIS മാനദണ്ഡ കൗൺസിലുകൾ',
    division_councils_sub: '8 സാങ്കേതിക ഡിവിഷനുകൾ · 14,000+ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ',
    standards_count_suffix: 'മാനദണ്ഡങ്ങൾ',

    // Services
    services_badge: 'ഔദ്യോഗിക BIS പദ്ധതികൾ',
    services_title: 'ബ്യൂറോ ഓഫ് ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് സേവനങ്ങൾ',
    services_sub: 'ഉൽപ്പന്ന സർട്ടിഫിക്കേഷൻ, സ്റ്റാൻഡേർഡ്സ് ക്ലബ്ബുകൾ, NITS പരിശീലനം.',
    target_eligibility: 'യോഗ്യത',
    open_scheme_portal: 'ഔദ്യോഗിക പോർട്ടൽ തുറക്കുക',

    // NABL Labs
    labs_title: 'ഓൾ-ഇന്ത്യ പരിശോധനാ ലാബുകളുടെ ഡയറക്ടറി',
    labs_sub: 'ഇന്ത്യയിലുടനീളമുള്ള ഔദ്യോഗിക BIS-അംഗീകൃത NABL ലാബുകൾ',
    current_facility_label: 'നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത സ്ഥാപനം',
    primary_facility_badge: 'പ്രാഥമിക സ്ഥാപനം',
    filter_region: 'സംസ്ഥാനം തിരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
    filter_scope: 'പരിശോധനാ വ്യാപ്തി അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
    showing_facilities: 'അംഗീകൃത ലാബുകൾ കാണിക്കുന്നു',
    near_you: 'നിങ്ങളുടെ അടുത്ത്',
    proximity: 'ദൂരം',
    accredited_scope_label: 'അംഗീകൃത പരിശോധനാ പരിധി',
    open_google_maps: 'ഗൂഗിൾ മാപ്സിൽ തുറക്കുക',

    // Settings
    settings_title: 'ക്രമീകരണങ്ങൾ',
    app_language_title: 'ആപ്പ് ഭാഷ & ഇന്റർഫേസ്',
    app_language_sub: 'എല്ലാ പേജുകളിലും സ്ഥിര ഭാഷ സജ്ജമാക്കുന്നു.',
    notifications_title: 'അറിയിപ്പുകൾ',
    gazette_alerts: 'QCO ഗസറ്റ് അറിയിപ്പുകൾ',
    gazette_alerts_sub: 'പുതിയ മാനദണ്ഡങ്ങൾ വരുമ്പോൾ അടിയന്തിര അറിയിപ്പ്',
    audit_reminders: 'ഓഡിറ്റ് ഓർമ്മപ്പെടുത്തലുകൾ',
    audit_reminders_sub: 'ലാബ് പരിശോധനാ രേഖകൾക്കുള്ള ഓർമ്മപ്പെടുത്തലുകൾ',
    back: 'തിരികെ',

    // Profile
    profile_title: 'എന്റർപ്രൈസ് ക്രെഡൻഷ്യലുകൾ',
    profile_sub: 'ബിഐഎസ് ലൈസൻസി രജിസ്ട്രിയും അനുസരണ രേഖകളും',
    tab_licenses: 'ലൈസൻസുകൾ',
    tab_audit: 'ഓഡിറ്റും സന്ദർശനങ്ങളും',
    tab_officer: 'ബിഐഎസ് ഓഫീസർ',
    audit_score: 'ഓഡിറ്റ് സ്കോർ',
    active_licenses: 'സജീവ ലൈസൻസുകൾ',
    next_surveillance: 'അടുത്ത പരിശോധന',
    factory_premises: 'ഫാക്ടറി പരിസരം',
    auth_signatory: 'അധികൃത ഒപ്പുവച്ചയാൾ',
    factory_unit: 'ഫാക്ടറി യൂണിറ്റ്',
    lab_clearance: 'ലാബ് ക്ലിയറൻസ്',
    surveillance_visit: 'നിരീക്ഷണ സന്ദർശനം',
    view_license_cert: 'ലൈസൻസ് സർട്ടിഫിക്കറ്റ് കാണുക',
    standard_specs: 'മാനദണ്ഡ സ്പെസിഫിക്കേഷനുകൾ',
    next_audit_title: 'അടുത്ത ഓഡിറ്റ്: 18-Nov-2024',
    surveillance_desc: 'ഇരുചക്ര വാഹന ഹെൽമെറ്റുകൾക്കുള്ള (IS 4151) നിരീക്ഷണ പരിശോധന. ടെസ്റ്റ് രേഖകൾ ഡോക്യുമെന്റ് വോൾട്ടിൽ സൂക്ഷിക്കുക.',
    prepare_audit_docs: 'ഓഡിറ്റ് രേഖകൾ തയ്യാറാക്കുക',
    compliance_lifecycle: 'കംപ്ലയൻസ് ലൈഫ് സൈക്കിൾ',
    branch_office: 'ബ്രാഞ്ച് ഓഫീസ്',
    office_hours: 'ഓഫീസ് സമയം',
    email_branch: 'ശാഖയിലേക്ക് ഇമെയിൽ അയക്കുക',

    // Ask Extra
    chip_prompt_helmet: 'ഇരുചക്ര വാഹന ഹെൽമെറ്റ് മാനദണ്ഡം IS 4151',
    chip_prompt_bottle: 'സ്റ്റെയിൻലെസ് സ്റ്റീൽ കുപ്പി IS 17803 പരിശോധിക്കുക',
    chip_prompt_labs: 'ചെന്നൈയിലെ പരിശോധനാ ലാബുകൾ',
    chip_prompt_fake_isi: 'വ്യാജ ISI മാർക്ക് എങ്ങനെ തിരിച്ചറിയാം',
    chip_prompt_hallmark: 'സ്വർണ്ണ ഹാൾമാർക്കും HUID പരിശോധനയും',
    chip_prompt_complaint: 'ഉപഭോക്തൃ പരാതി രജിസ്റ്റർ ചെയ്യുക 1800-11-4000',
    praman_disclaimer: 'സഹായത്തിന് മാത്രം. BIS CARE അല്ലെങ്കിൽ bis.gov.in-ൽ ഔദ്യോഗികമായി പരിശോധിക്കുക.',

    // Standards Extra
    resolved_classification: 'സ്ഥിരീകരിച്ച വർഗ്ഗീകരണം',
    applicable_standard: 'ബാധകമായ മാനദണ്ഡം',
    certification_scheme: 'സർട്ടിഫിക്കേഷൻ പദ്ധതി',
    enforcing_authority: 'നടപ്പിലാക്കുന്ന അധികാരിയും ഗസറ്റും:',
    mandatory_testing_scope: 'നിർബന്ധിത പരിശോധനാ പരിധി:',
    open_bis_registry: 'ഔദ്യോഗിക BIS രജിസ്ട്രി പേജ് തുറക്കുക',
    related_standards: 'ബന്ധപ്പെട്ട മാനദണ്ഡങ്ങൾ',

    // Services Extra
    cat_all: 'എല്ലാം',
    cat_industry: 'വ്യവസായവും നിർമ്മാണവും',
    cat_youth: 'യുവജനങ്ങളും വിദ്യാഭ്യാസവും',
    cat_capacity: 'ശേഷി വികസനം',
    cat_testing: 'പരിശോധനയും കാലിബ്രേഷനും',
    cat_citizen: 'പൗര സേവനങ്ങൾ',
    cat_digital: 'ഡിജിറ്റൽ പരിശോധന',

    // Vault
    vault_title: 'ഡോക്യുമെന്റ് വോൾട്ട്',
    upload_doc_title: 'സർട്ടിഫിക്കറ്റ് അല്ലെങ്കിൽ ടെസ്റ്റ് റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    upload_doc_sub: '15MB വരെയുള്ള PDF, JPG അല്ലെങ്കിൽ PNG · തൽക്ഷണ OCR തിരിച്ചറിയൽ',
    stored_certs: 'സംഭരിച്ച സർട്ടിഫിക്കറ്റുകൾ',

    // Dashboard Extra
    labs_dir_title: 'ഓൾ-ഇന്ത്യ പരിശോധനാ ലാബുകളുടെ ഡയറക്ടറി',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'ഉൽപ്പന്നവും നഗരവും അനുസരിച്ച് അംഗീകൃത ലാബുകൾ കണ്ടെത്തുക',
    services_programmes_title: 'BIS സേവനങ്ങളും പദ്ധതികളും',
    services_programmes_badge: 'പദ്ധതികൾ',
    services_programmes_sub: 'സ്റ്റാൻഡേർഡ്സ് ക്ലബ്ബുകൾ, NITS പരിശീലനം, LRS ലാബ് പദ്ധതി & സർട്ടിഫിക്കേഷൻ',
    consumer_corner_title: 'ഉപഭോക്തൃ സംരക്ഷണവും പരാതി പരിഹാരവും',
    national_consumer_helpline: 'ദേശീയ ഉപഭോക്തൃ ഹെൽപ്പ്‌ലൈൻ',
    toll_free: '1800-11-4000 (ടോൾ ഫ്രീ)',
    call_now: 'ഇപ്പോൾ വിളിക്കുക',
    consumer_card_desc: 'വ്യാജ ISI മാർക്കുകൾ അല്ലെങ്കിൽ നിർബന്ധിത 6 അക്ക HUID ഇല്ലാതെ വിൽക്കുന്ന സ്വർണ്ണാഭരണങ്ങളെക്കുറിച്ച് നേരിട്ട് BIS-ൽ പരാതിപ്പെടുക.',
    bis_grievance_portal: 'BIS പരാതി പോർട്ടൽ',
    download_bis_care: 'BIS CARE ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
    chip_helmets: 'IS 4151 ഹെൽമെറ്റുകൾ',
    chip_gold: 'സ്വർണ്ണ ഹാൾമാർക്ക് & HUID',
    chip_labs: 'NABL ലാബുകൾ കണ്ടെത്തുക',
  },

  mr: {
    // Tabs
    tab_dashboard: 'डॅशबोर्ड',
    tab_praman_ai: 'प्रमाण AI',
    tab_standards: 'मानके',
    tab_services: 'सेवा',
    tab_nabl_labs: 'NABL प्रयोगशाळा',
    tab_enterprise: 'उद्योग',

    // Dashboard
    greeting_title: 'शुभ संध्याकाळ, श्रीपती',
    greeting_sub: 'BIS परवानाधारक डॅशबोर्ड',
    enterprise_status: 'उद्योग अनुपालन स्थिती',
    qco_compliant: 'QCO अनुपालन पूर्ण',
    registered_facility: 'नोंदणीकृत प्रकल्प',
    certified_product_lines: 'प्रमाणित उत्पादने · 2 सक्रिय ISI परवाने',
    two_wheeler_helmets: 'दुचाकी हेल्मेट',
    stainless_steel_flasks: 'स्टेनलेस स्टील बाटल्या व फ्लास्क',
    valid_2027: 'वैधता 2027',
    valid_2026: 'वैधता 2026',
    manage_enterprise: 'उद्योग माहिती व्यवस्थापित करा',
    ask_praman_badge: 'AI अनुपालन सहाय्यक',
    live_gazette_sync: 'थेट राजपत्र सिंक',
    ask_praman_title: 'प्रमाण अनुपालन सहाय्यकाला विचारा',
    ask_praman_sub: 'भारतीय भाषांमध्ये विचारा. अधिकृत BIS राजपत्रांमधून त्वरित माहिती.',
    search_praman_placeholder: 'IS 4151, अनिवार्य QCO किंवा जवळच्या लॅबबद्दल विचारा',
    quick_regulatory_services: 'जलद नियामक सेवा',
    qco_checker_title: 'QCO आणि मानके तपासक',
    qco_checker_badge: 'अनिवार्य',
    qco_checker_sub: '14,000+ भारतीय मानके शोधा',
    doc_vault_title: 'कागदपत्र वॉल्ट',
    doc_vault_badge: '3 प्रमाणपत्रे',
    doc_vault_sub: '3 सत्यापित प्रमाणपत्रे आणि चाचणी अहवाल',

    // Praman AI
    praman_header_title: 'प्रमाण अनुपालन सहाय्यक',
    praman_header_sub: 'अधिकृत BIS नियामक ज्ञानकोश',
    auto_lang_banner: 'भाषा ओळख सक्रिय · मराठी, इंग्रजी, हिंदी, तमिळ, तेलुगू...',
    praman_welcome: 'नमस्कार, मी प्रमाण आहे, तुमचा भारतीय मानक ब्युरो सहाय्यक. तुम्ही मराठी, इंग्रजी, हिंदी इत्यादी भाषांमध्ये विचारू शकता.',
    ask_input_placeholder: 'मराठी किंवा इंग्रजीत विचारा...',
    chat_sessions: 'चॅट सत्रे',
    new_chat: 'नवीन चॅट',
    pinned_chats: 'पिन केलेल्या चॅट्स',
    recent_chats: 'अलीकडील चॅट्स',
    pin_chat: 'पिन करा',
    unpin_chat: 'अनपिन करा',
    rename_chat: 'नाव बदला',
    delete_chat: 'हटवा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    rename_chat_title: 'चॅटचे नाव बदला',
    enter_new_title: 'नवीन शीर्षक प्रविष्ट करा',
    no_chats_found: 'कोणतेही चॅट सत्र सापडले नाही',

    // Standards
    standards_title: 'मानके आणि QCO पडताळणी',
    standards_sub: 'अधिकृत भारतीय मानक ब्युरो नोंदवही',
    verify_compliance_prompt: 'उत्पादन अनुपालन आणि अनिवार्य मानके तपासा',
    standards_input_placeholder: 'उदा. हेल्मेट, IS 4151, प्लग',
    run_qco_check_btn: 'QCO ज्ञान आलेख चाचणी चालवा',
    jurisdiction_label: 'नियामक अधिकार क्षेत्र',
    change_zone_btn: 'झोन बदला',
    jurisdiction_desc: 'हे सेटिंग तुमच्या BIS कार्यालयाशी आणि 250 किमी मधील NABL प्रयोगशाळांशी जोडते.',
    division_councils_title: 'BIS मानके विभाग परिषद',
    division_councils_sub: '8 तांत्रिक विभाग · 14,000+ भारतीय मानके',
    standards_count_suffix: 'मानके',

    // Services
    services_badge: 'अधिकृत BIS योजना',
    services_title: 'भारतीय मानक ब्युरो सेवा',
    services_sub: 'उत्पादन प्रमाणीकरण, मानके क्लब आणि ग्राहक व्यवहार उपक्रम.',
    target_eligibility: 'पात्रता',
    open_scheme_portal: 'अधिकृत पोर्टल उघडा',

    // NABL Labs
    labs_title: 'अखिल भारतीय चाचणी प्रयोगशाळा निर्देशिका',
    labs_sub: 'भारतातील अधिकृत BIS-मान्यताप्राप्त NABL प्रयोगशाळा',
    current_facility_label: 'तुमची नोंदणीकृत सुविधा',
    primary_facility_badge: 'प्राथमिक सुविधा',
    filter_region: 'राज्य / प्रदेशानुसार फिल्टर करा',
    filter_scope: 'उत्पादन चाचणी व्याप्तीनुसार फिल्टर करा',
    showing_facilities: 'प्रत्यायित प्रयोगशाळा दर्शवित आहे',
    near_you: 'तुमच्या जवळ',
    proximity: 'अंतर',
    accredited_scope_label: 'प्रत्यायित चाचणी व्याप्ती',
    open_google_maps: 'गुगल मॅप्सवर उघडा',

    // Settings
    settings_title: 'सेटिंग्ज आणि प्राधान्ये',
    app_language_title: 'ॲप भाषा आणि इंटरफेस',
    app_language_sub: 'सर्व पृष्ठांवर डीफॉल्ट भाषा सेट करते.',
    notifications_title: 'सूचना प्राधान्ये',
    gazette_alerts: 'QCO राजपत्र सूचना',
    gazette_alerts_sub: 'नवीन मानकांसाठी त्वरित सूचना',
    audit_reminders: 'ऑडिट स्मरणपत्रे',
    audit_reminders_sub: 'त्रैमासिक चाचणी नोंदी स्मरणपत्रे',
    back: 'मागे',

    // Profile
    profile_title: 'उद्योग ओळखपत्रे',
    profile_sub: 'BIS परवानाधारक नोंदवही आणि अनुपालन नोंदी',
    tab_licenses: 'परवाने',
    tab_audit: 'ऑडिट आणि भेटी',
    tab_officer: 'BIS अधिकारी',
    audit_score: 'ऑडिट स्कोअर',
    active_licenses: 'सक्रिय परवाने',
    next_surveillance: 'पुढील तपासणी',
    factory_premises: 'कारखाना परिसर',
    auth_signatory: 'अधिकृत स्वाक्षरीकर्ता',
    factory_unit: 'कारखाना युनिट',
    lab_clearance: 'लॅब क्लिअरन्स',
    surveillance_visit: 'देखरेख भेट',
    view_license_cert: 'परवाना प्रमाणपत्र पहा',
    standard_specs: 'मानक तपशील',
    next_audit_title: 'पुढील ऑडिट: 18-Nov-2024',
    surveillance_desc: 'दुचाकी हेल्मेट (IS 4151) देखरेख तपासणी. कागदपत्र वॉल्टमध्ये चाचणी नोंदी ठेवा.',
    prepare_audit_docs: 'ऑडिट कागदपत्रे तयार करा',
    compliance_lifecycle: 'अनुपालन जीवनचक्र',
    branch_office: 'शाखा कार्यालय',
    office_hours: 'कार्यालयीन वेळ',
    email_branch: 'शाखेला ईमेल करा',

    // Ask Extra
    chip_prompt_helmet: 'दुचाकी हेल्मेट मानक IS 4151',
    chip_prompt_bottle: 'स्टेनलेस स्टील बाटली IS 17803 तपासा',
    chip_prompt_labs: 'चेन्नईमधील चाचणी प्रयोगशाळा',
    chip_prompt_fake_isi: 'बनावट ISI मार्क कसा तपासावा',
    chip_prompt_hallmark: 'सुवर्ण हॉलमार्क आणि HUID पडताळणी',
    chip_prompt_complaint: 'ग्राहक तक्रार नोंदवा 1800-11-4000',
    praman_disclaimer: 'फक्त मार्गदर्शनासाठी. BIS CARE किंवा bis.gov.in वर अधिकृत पडताळणी करा.',

    // Standards Extra
    resolved_classification: 'निश्चित वर्गीकरण',
    applicable_standard: 'लागू मानक',
    certification_scheme: 'प्रमाणीकरण योजना',
    enforcing_authority: 'अंमलबजावणी प्राधिकरण आणि राजपत्र:',
    mandatory_testing_scope: 'अनिवार्य चाचणी व्याप्ती:',
    open_bis_registry: 'अधिकृत BIS मानक नोंदणी पृष्ठ उघडा',
    related_standards: 'संबंधित मानके',

    // Services Extra
    cat_all: 'सर्व',
    cat_industry: 'उद्योग आणि उत्पादन',
    cat_youth: 'युवा आणि शिक्षण',
    cat_capacity: 'क्षमता बांधणी',
    cat_testing: 'चाचणी आणि कॅलिब्रेशन',
    cat_citizen: 'नागरिक सेवा',
    cat_digital: 'डिजिटल पडताळणी',

    // Vault
    vault_title: 'कागदपत्र वॉल्ट',
    upload_doc_title: 'प्रमाणपत्र किंवा चाचणी अहवाल अपलोड करा',
    upload_doc_sub: '15MB पर्यंत PDF, JPG किंवा PNG · त्वरित OCR ओळख',
    stored_certs: 'साठवलेली प्रमाणपत्रे',

    // Dashboard Extra
    labs_dir_title: 'अखिल भारतीय चाचणी प्रयोगशाळा निर्देशिका',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'उत्पादन आणि शहरानुसार मान्यताप्राप्त लॅब्स शोधा',
    services_programmes_title: 'BIS सेवा आणि उपक्रम',
    services_programmes_badge: 'योजना',
    services_programmes_sub: 'मानके क्लब, NITS प्रशिक्षण, LRS लॅब योजना आणि प्रमाणीकरण',
    consumer_corner_title: 'ग्राहक संरक्षण आणि तक्रार निवारण',
    national_consumer_helpline: 'राष्ट्रीय ग्राहक हेल्पलाइन',
    toll_free: '1800-11-4000 (टोल-फ्री)',
    call_now: 'आता कॉल करा',
    consumer_card_desc: 'बनावट ISI मार्क किंवा अनिवार्य 6-अंकी HUID कोड नसलेल्या सोन्याच्या दागिन्यांची थेट BIS कडे तक्रार करा.',
    bis_grievance_portal: 'BIS तक्रार निवारण पोर्टल',
    download_bis_care: 'BIS CARE ॲप डाउनलोड करा',
    chip_helmets: 'IS 4151 हेल्मेट',
    chip_gold: 'सुवर्ण हॉलमार्क & HUID',
    chip_labs: 'NABL प्रयोगशाळा शोधा',
  },

  bn: {
    // Tabs
    tab_dashboard: 'ড্যাশবোর্ড',
    tab_praman_ai: 'প্রমাণ AI',
    tab_standards: 'মানক',
    tab_services: 'পরিষেবা',
    tab_nabl_labs: 'NABL ল্যাব',
    tab_enterprise: 'এন্টারপ্রাইজ',

    // Dashboard
    greeting_title: 'শুভ সন্ধ্যা, শ্রীপতি',
    greeting_sub: 'BIS লাইসেন্সধারীর ড্যাশবোর্ড',
    enterprise_status: 'এন্টারপ্রাইজ সম্মতি স্থিতি',
    qco_compliant: 'QCO অনুগত',
    registered_facility: 'নিবন্ধিত কারখানা',
    certified_product_lines: 'প্রত্যয়িত পণ্য · ২ সক্রিয় ISI লাইসেন্স',
    two_wheeler_helmets: 'দ্বিচক্র যান হেলমেট',
    stainless_steel_flasks: 'স্টেইনলেস স্টিল ফ্লাস্ক ও জলের বোতল',
    valid_2027: 'বৈধ ২০২৭',
    valid_2026: 'বৈধ ২০২৬',
    manage_enterprise: 'শংসাপত্র পরিচালনা করুন',
    ask_praman_badge: 'AI সম্মতি সহকারী',
    live_gazette_sync: 'লাইভ গেজেট সিঙ্ক',
    ask_praman_title: 'প্রমাণ সম্মতি সহকারীকে জিজ্ঞাসা করুন',
    ask_praman_sub: 'ভারতীয় ভাষায় জিজ্ঞাসা করুন। অফিসিয়াল BIS গেজেট থেকে তাৎক্ষণিক তথ্য।',
    search_praman_placeholder: 'IS 4151, বাধ্যতামূলক QCO বা নিকটতম ল্যাব সম্পর্কে জিজ্ঞাসা করুন',
    quick_regulatory_services: 'নিয়ন্ত্রক পরিষেবা',
    qco_checker_title: 'QCO ও মানক পরীক্ষক',
    qco_checker_badge: 'বাধ্যতামূলক',
    qco_checker_sub: '১৪,০০০+ ভারতীয় মানক অনুসন্ধান করুন',
    doc_vault_title: 'নথি ভল্ট',
    doc_vault_badge: '৩ প্রমাণপত্র',
    doc_vault_sub: '৩ যাচাইকৃত শংসাপত্র ও NABL রিপোর্ট',

    // Praman AI
    praman_header_title: 'প্রমাণ সম্মতি সহকারী',
    praman_header_sub: 'অফিসিয়াল BIS জ্ঞানভাণ্ডার',
    auto_lang_banner: 'স্বয়ংক্রিয় ভাষা সনাক্তকরণ সক্রিয় · বাংলা, ইংরেজি, হিন্দি, তামিল...',
    praman_welcome: 'নমস্কার, আমি প্রমাণ, আপনার ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস সহকারী।',
    ask_input_placeholder: 'বাংলায় বা ইংরেজিতে জিজ্ঞাসা করুন...',
    chat_sessions: 'চ্যাট সেশন',
    new_chat: 'নতুন চ্যাট',
    pinned_chats: 'পিন করা চ্যাট',
    recent_chats: 'সাম্প্রতিক চ্যাট',
    pin_chat: 'পিন করুন',
    unpin_chat: 'আনপিন করুন',
    rename_chat: 'নাম পরিবর্তন',
    delete_chat: 'মুছে ফেলুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    rename_chat_title: 'চ্যাটের নাম পরিবর্তন করুন',
    enter_new_title: 'নতুন শিরোনাম লিখুন',
    no_chats_found: 'কোনো চ্যাট সেশন পাওয়া যায়নি',

    // Standards
    standards_title: 'মানক এবং QCO যাচাইকরণ',
    standards_sub: 'অফিসিয়াল ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস রেজিস্ট্রি',
    verify_compliance_prompt: 'পণ্য সম্মতি এবং বাধ্যতামূলক মানক যাচাই করুন',
    standards_input_placeholder: 'যেমন হেলমেট, IS 4151, প্লাগ',
    run_qco_check_btn: 'QCO জ্ঞান গ্রাফ পরীক্ষা চালান',
    jurisdiction_label: 'নিয়ন্ত্রক এখতিয়ার',
    change_zone_btn: 'অঞ্চল পরিবর্তন',
    jurisdiction_desc: 'এটি আপনার BIS শাখা এবং ২৫০ কিমির মধ্যে NABL ল্যাব সংযুক্ত করে।',
    division_councils_title: 'BIS মানক বিভাগ পরিষদ',
    division_councils_sub: '৮টি প্রযুক্তিগত বিভাগ · ১৪,০০০+ ভারতীয় মানক',
    standards_count_suffix: 'মানক',

    // Services
    services_badge: 'অফিসিয়াল BIS প্রকল্প',
    services_title: 'ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস পরিষেবা',
    services_sub: 'পণ্য শংসাপত্র, মানক ক্লাব এবং ভোক্তা বিষয়ক উদ্যোগ।',
    target_eligibility: 'যোগ্যতা',
    open_scheme_portal: 'অফিসিয়াল পোর্টাল খুলুন',

    // NABL Labs
    labs_title: 'নিখিল ভারত পরীক্ষাগার ডিরেক্টরি',
    labs_sub: 'ভারতজুড়ে অফিসিয়াল BIS-স্বীকৃত NABL ল্যাব',
    current_facility_label: 'আপনার নিবন্ধিত সুবিধা',
    primary_facility_badge: 'প্রাথমিক সুবিধা',
    filter_region: 'অঞ্চল / রাজ্য অনুযায়ী ফিল্টার করুন',
    filter_scope: 'পণ্য পরীক্ষার পরিধি অনুযায়ী ফিল্টার করুন',
    showing_facilities: 'স্বীকৃত ল্যাব দেখানো হচ্ছে',
    near_you: 'আপনার কাছাকাছি',
    proximity: 'দূরত্ব',
    accredited_scope_label: 'স্বীকৃত পরীক্ষার পরিধি',
    open_google_maps: 'গুগল ম্যাপে খুলুন',

    // Settings
    settings_title: 'সেটিংস এবং পছন্দসমূহ',
    app_language_title: 'অ্যাপের ভাষা ও ইন্টারফেস',
    app_language_sub: 'সমস্ত পৃষ্ঠায় ডিফল্ট ভাষা সেট করে।',
    notifications_title: 'বিজ্ঞপ্তি পছন্দসমূহ',
    gazette_alerts: 'QCO গেজেট বিজ্ঞপ্তি',
    gazette_alerts_sub: 'নতুন মানক প্রকাশের সাথে সাথে সতর্কবার্তা',
    audit_reminders: 'অডিট অনুস্মারক',
    audit_reminders_sub: 'ত্রৈমাসিক পরীক্ষা রেকর্ডের অনুস্মারক',
    back: 'ফিরে যান',

    // Profile
    profile_title: 'এন্টারপ্রাইজ শংসাপত্র',
    profile_sub: 'BIS লাইসেন্সধারী রেজিস্ট্রি এবং সম্মতি রেকর্ড',
    tab_licenses: 'লাইসেন্স',
    tab_audit: 'অডিট ও পরিদর্শন',
    tab_officer: 'BIS কর্মকর্তা',
    audit_score: 'অডিট স্কোর',
    active_licenses: 'সক্রিয় লাইসেন্স',
    next_surveillance: 'পরবর্তী নজরদারি',
    factory_premises: 'কারখানা প্রাঙ্গণ',
    auth_signatory: 'অনুমোদিত স্বাক্ষরকারী',
    factory_unit: 'কারখানা ইউনিট',
    lab_clearance: 'ল্যাব ক্লিয়ারেন্স',
    surveillance_visit: 'নজরদারি পরিদর্শন',
    view_license_cert: 'লাইসেন্স শংসাপত্র দেখুন',
    standard_specs: 'মানক বিবরণ',
    next_audit_title: 'পরবর্তী অডিট: 18-Nov-2024',
    surveillance_desc: 'দ্বিচক্র যান হেলমেট (IS 4151) নজরদারি পরিদর্শন। নথি ভল্টে পরীক্ষার রেকর্ড রাখুন।',
    prepare_audit_docs: 'অডিট নথি প্রস্তুত করুন',
    compliance_lifecycle: 'সম্মতি জীবনচক্র',
    branch_office: 'শাখা অফিস',
    office_hours: 'অফিস সময়',
    email_branch: 'শাখায় ইমেল করুন',

    // Ask Extra
    chip_prompt_helmet: 'দ্বিচক্র যান হেলমেট মানক IS 4151',
    chip_prompt_bottle: 'স্টেইনলেস স্টিল বোতল IS 17803 যাচাই করুন',
    chip_prompt_labs: 'চেন্নাইয়ের পরীক্ষা ল্যাব',
    chip_prompt_fake_isi: 'নকল ISI চিহ্ন কীভাবে যাচাই করবেন',
    chip_prompt_hallmark: 'স্বর্ণ হলমার্ক এবং HUID যাচাইকরণ',
    chip_prompt_complaint: 'ভোক্তা অভিযোগ দায়ের করুন 1800-11-4000',
    praman_disclaimer: 'শুধুমাত্র সহায়তার জন্য। BIS CARE বা bis.gov.in-এ অফিসিয়াল যাচাই করুন।',

    // Standards Extra
    resolved_classification: 'নির্ধারিত শ্রেণিবিন্যাস',
    applicable_standard: 'প্রযোজ্য মানক',
    certification_scheme: 'শংসাপত্র প্রকল্প',
    enforcing_authority: 'প্রয়োগকারী কর্তৃপক্ষ ও গেজেট:',
    mandatory_testing_scope: 'বাধ্যতামূলক পরীক্ষার পরিধি:',
    open_bis_registry: 'অফিসিয়াল BIS মানক রেজিস্ট্রি পৃষ্ঠা খুলুন',
    related_standards: 'সম্পর্কিত মানক',

    // Services Extra
    cat_all: 'সকল',
    cat_industry: 'শিল্প ও উৎপাদন',
    cat_youth: 'যুব ও শিক্ষা',
    cat_capacity: 'দক্ষতা বৃদ্ধি',
    cat_testing: 'পরীক্ষা ও ক্রমাঙ্কন',
    cat_citizen: 'নাগরিক পরিষেবা',
    cat_digital: 'ডিজিটাল যাচাইকরণ',

    // Vault
    vault_title: 'নথি ভল্ট',
    upload_doc_title: 'শংসাপত্র বা পরীক্ষার রিপোর্ট আপলোড করুন',
    upload_doc_sub: '১৫এমবি পর্যন্ত PDF, JPG বা PNG · তাৎক্ষণিক OCR শনাক্তকরণ',
    stored_certs: 'সংরক্ষিত শংসাপত্র',

    // Dashboard Extra
    labs_dir_title: 'নিখিল ভারত পরীক্ষাগার ডিরেক্টরি',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'পণ্য এবং শহর অনুযায়ী স্বীকৃত ল্যাব খুঁজুন',
    services_programmes_title: 'BIS পরিষেবা এবং প্রকল্প',
    services_programmes_badge: 'প্রকল্প',
    services_programmes_sub: 'স্ট্যান্ডার্ডস ক্লাব, NITS প্রশিক্ষণ, LRS ল্যাব স্কিম ও শংসাপত্র',
    consumer_corner_title: 'ভোক্তা সুরক্ষা ও অভিযোগ নিষ্পত্তি',
    national_consumer_helpline: 'জাতীয় ভোক্তা হেল্পলাইন',
    toll_free: '1800-11-4000 (টোল-ফ্রি)',
    call_now: 'এখনই কল করুন',
    consumer_card_desc: 'নকল ISI মার্ক বা বাধ্যতামূলক ৬-সংখ্যার HUID কোড ছাড়া বিক্রি হওয়া সোনার গয়না সম্পর্কে সরাসরি BIS-এ অভিযোগ জানান।',
    bis_grievance_portal: 'BIS অভিযোগ পোর্টাল',
    download_bis_care: 'BIS CARE অ্যাপ ডাউনলোড করুন',
    chip_helmets: 'IS 4151 হেলমেট',
    chip_gold: 'স্বর্ণ হলমার্ক ও HUID',
    chip_labs: 'NABL ল্যাব খুঁজুন',
  },

  or: {
    // Tabs
    tab_dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    tab_praman_ai: 'ପ୍ରମାଣ AI',
    tab_standards: 'ମାନକ',
    tab_services: 'ସେବା',
    tab_nabl_labs: 'NABL ଲାବୋରେଟୋରୀ',
    tab_enterprise: 'ଉଦ୍ୟୋଗ',

    // Dashboard
    greeting_title: 'ଶୁଭ ସନ୍ଧ୍ୟା, ଶ୍ରୀପତି',
    greeting_sub: 'BIS ଲାଇସେନ୍ସପ୍ରାପ୍ତ ଡ୍ୟାସବୋର୍ଡ',
    enterprise_status: 'ଉଦ୍ୟୋଗ ଅନୁପାଳନ ସ୍ଥିତି',
    qco_compliant: 'QCO ଅନୁପାଳିତ',
    registered_facility: 'ପଞ୍ଜୀକୃତ କାରଖାନା',
    certified_product_lines: 'ପ୍ରମାଣିତ ଉତ୍ପାଦ · ୨ ସକ୍ରିୟ ISI ଲାଇସେନ୍ସ',
    two_wheeler_helmets: 'ଦୁଇ ଚକିଆ ହେଲମେଟ',
    stainless_steel_flasks: 'ଷ୍ଟେନଲେସ ଷ୍ଟିଲ ଫ୍ଲାସ୍କ ଏବଂ ବୋତଲ',
    valid_2027: 'ବୈଧ ୨୦୨୭',
    valid_2026: 'ବୈଧ ୨୦୨୬',
    manage_enterprise: 'ବିବରଣୀ ପରିଚାଳନା କରନ୍ତୁ',
    ask_praman_badge: 'AI ସହାୟକ',
    live_gazette_sync: 'ଲାଇଭ ଗେଜେଟ ସିଙ୍କ',
    ask_praman_title: 'ପ୍ରମାଣ ସହାୟକଙ୍କୁ ପଚାରନ୍ତୁ',
    ask_praman_sub: 'ଭାରତୀୟ ଭାଷାରେ ପଚାରନ୍ତୁ। ସରକାରୀ BIS ଗେଜେଟରୁ ତତକ୍ଷଣାତ ସୂଚନା।',
    search_praman_placeholder: 'IS 4151, ବାଧ୍ୟତାମୂଳକ QCO କିମ୍ବା ନିକଟସ୍ଥ ଲାବ୍ ବିଷୟରେ ପଚାରନ୍ତୁ',
    quick_regulatory_services: 'ନିୟାମକ ସେବା',
    qco_checker_title: 'QCO ଏବଂ ମାନକ ଯାଞ୍ଚକାରୀ',
    qco_checker_badge: 'ବାଧ୍ୟତାମୂଳକ',
    qco_checker_sub: '୧୪,୦୦୦+ ଭାରତୀୟ ମାନକ ଖୋଜନ୍ତୁ',
    doc_vault_title: 'ଦଲିଲ ଭଲ୍ଟ',
    doc_vault_badge: '୩ ପ୍ରମାଣପତ୍ର',
    doc_vault_sub: '୩ ଯାଞ୍ଚ ହୋଇଥିବା ପ୍ରମାଣପତ୍ର ଏବଂ NABL ରିପୋର୍ଟ',

    // Praman AI
    praman_header_title: 'ପ୍ରମାଣ ଅନୁପାଳନ ସହାୟକ',
    praman_header_sub: 'ସରକାରୀ BIS ଜ୍ଞାନକୋଷ',
    auto_lang_banner: 'ଭାଷା ଚିହ୍ନଟ ସକ୍ରିୟ · ଓଡ଼ିଆ, ଇଂରାଜୀ, ହିନ୍ଦୀ, ତାମିଲ...',
    praman_welcome: 'ନମସ୍କାର, ମୁଁ ପ୍ରମାଣ, ଆପଣଙ୍କ BIS ସହାୟକ। ଆପଣ ଓଡ଼ିଆ କିମ୍ବା ଇଂରାଜୀରେ ପଚାରିପାରିବେ।',
    ask_input_placeholder: 'ଓଡ଼ିଆ କିମ୍ବା ଇଂରାଜୀରେ ପଚାରନ୍ତୁ...',
    chat_sessions: 'ଚାଟ୍ ସେସନ',
    new_chat: 'ନୂଆ ଚାଟ୍',
    pinned_chats: 'ପିନ୍ ହୋଇଥିବା ଚାଟ୍',
    recent_chats: 'ସାମ୍ପ୍ରତିକ ଚାଟ୍',
    pin_chat: 'ପିନ୍ କରନ୍ତୁ',
    unpin_chat: 'ଅନପିନ୍ କରନ୍ତୁ',
    rename_chat: 'ନାମ ବଦଳାନ୍ତୁ',
    delete_chat: 'ଡିଲିଟ୍ କରନ୍ତୁ',
    save: 'ସେଭ୍ କରନ୍ତୁ',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    rename_chat_title: 'ଚାଟ୍ ଶୀର୍ଷକ ବଦଳାନ୍ତୁ',
    enter_new_title: 'ନୂଆ ନାମ ଲେଖନ୍ତୁ',
    no_chats_found: 'କୌଣସି ଚାଟ୍ ମିଳିଲା ନାହିଁ',

    // Standards
    standards_title: 'ମାନକ ଏବଂ QCO ଯାଞ୍ଚ',
    standards_sub: 'ସରକାରୀ ଭାରତୀୟ ମାନକ ବ୍ୟୁରୋ ରେଜିଷ୍ଟ୍ରି',
    verify_compliance_prompt: 'ଉତ୍ପାଦ ଅନୁପାଳନ ଏବଂ ବାଧ୍ୟତାମୂଳକ ମାନକ ଯାଞ୍ଚ କରନ୍ତୁ',
    standards_input_placeholder: 'ଯଥା ହେଲମେଟ, IS 4151, ପ୍ଲଗ',
    run_qco_check_btn: 'QCO ଯାଞ୍ଚ ଚଲାନ୍ତୁ',
    jurisdiction_label: 'ନିୟାମକ ଅଧିକାର କ୍ଷେତ୍ର',
    change_zone_btn: 'ଅଞ୍ଚଳ ବଦଳାନ୍ତୁ',
    jurisdiction_desc: 'ଏହା ଆପଣଙ୍କ BIS ଶାଖା ଏବଂ ୨୫୦ କିମି ମଧ୍ୟରେ NABL ଲାବୋରେଟୋରୀ ସଂଯୋଗ କରେ।',
    division_councils_title: 'BIS ମାନକ ପରିଷଦ',
    division_councils_sub: '୮ଟି ବୈଷୟିକ ବିଭାଗ · ୧୪,୦୦୦+ ଭାରତୀୟ ମାନକ',
    standards_count_suffix: 'ମାନକ',

    // Services
    services_badge: 'ସରକାରୀ BIS ଯୋଜନା',
    services_title: 'ଭାରତୀୟ ମାନକ ବ୍ୟୁରୋ ସେବା',
    services_sub: 'ଉତ୍ପାଦ ପ୍ରମାଣୀକରଣ, ତାଲିମ ଏବଂ ଉପଭୋକ୍ତା ସଚେତନତା।',
    target_eligibility: 'ଯୋଗ୍ୟତା',
    open_scheme_portal: 'ସରକାରୀ ପୋର୍ଟାଲ ଖୋଲନ୍ତୁ',

    // NABL Labs
    labs_title: 'ସର୍ବଭାରତୀୟ ପରୀକ୍ଷାଗାର ତାଲିକା',
    labs_sub: 'ଭାରତରେ ଥିବା ସରକାରୀ BIS-ସ୍ୱୀକୃତିପ୍ରାପ୍ତ NABL ଲାବୋରେଟୋରୀ',
    current_facility_label: 'ଆପଣଙ୍କ ପଞ୍ଜୀକୃତ ସୁବିଧା',
    primary_facility_badge: 'ପ୍ରାଥମିକ ସୁବିଧା',
    filter_region: 'ରାଜ୍ୟ ଅନୁସାରେ ଫିଲ୍ଟର କରନ୍ତୁ',
    filter_scope: 'ପରୀକ୍ଷା ପରିସର ଅନୁସାରେ ଫିଲ୍ଟର କରନ୍ତୁ',
    showing_facilities: 'ସ୍ୱୀକୃତିପ୍ରାପ୍ତ ଲାବୋରେଟୋରୀ ଦର୍ଶାଯାଉଛି',
    near_you: 'ଆପଣଙ୍କ ନିକଟରେ',
    proximity: 'ଦୂରତା',
    accredited_scope_label: 'ସ୍ୱୀକୃତିପ୍ରାପ୍ତ ପରୀକ୍ଷା ପରିସର',
    open_google_maps: 'ଗୁଗଲ ମ୍ୟାପରେ ଖୋଲନ୍ତୁ',

    // Settings
    settings_title: 'ସେଟିଙ୍ଗ୍ସ',
    app_language_title: 'ଆପ୍ ଭାଷା',
    app_language_sub: 'ସମସ୍ତ ପୃଷ୍ଠାରେ ଡିଫଲ୍ଟ ଭାଷା ସେଟ୍ କରେ।',
    notifications_title: 'ବିଜ୍ଞପ୍ତି',
    gazette_alerts: 'QCO ଗେଜେଟ ସୂଚନା',
    gazette_alerts_sub: 'ନୂଆ ମାନକ ଘୋଷଣା ହେଲେ ତତକ୍ଷଣାତ ସୂଚନା',
    audit_reminders: 'ଅଡିଟ୍ ସ୍ମାରକୀ',
    audit_reminders_sub: 'ପରୀକ୍ଷା ରେକର୍ଡ ପାଇଁ ସ୍ମାରକୀ',
    back: 'ପଛକୁ',

    // Profile
    profile_title: 'ଉଦ୍ୟୋଗ ପରିଚୟପତ୍ର',
    profile_sub: 'BIS ଲାଇସେନ୍ସପ୍ରାପ୍ତ ରେଜିଷ୍ଟ୍ରି ଏବଂ ଅନୁପାଳନ ରେକର୍ଡ',
    tab_licenses: 'ଲାଇସେନ୍ସ',
    tab_audit: 'ଅଡିଟ୍ ଏବଂ ପରିଦର୍ଶନ',
    tab_officer: 'BIS ଅଧିକାରୀ',
    audit_score: 'ଅଡିଟ୍ ସ୍କୋର',
    active_licenses: 'ସକ୍ରିୟ ଲାଇସେନ୍ସ',
    next_surveillance: 'ପରବର୍ତ୍ତୀ ତଦାରଖ',
    factory_premises: 'କାରଖାନା ପରିସର',
    auth_signatory: 'ଅଧିକୃତ ଦସ୍ତଖତକାରୀ',
    factory_unit: 'କାରଖାନା ୟୁନିଟ୍',
    lab_clearance: 'ଲାବୋରେଟୋରୀ କ୍ଲିୟରାନ୍ସ',
    surveillance_visit: 'ତଦାରଖ ପରିଦର୍ଶନ',
    view_license_cert: 'ଲାଇସେନ୍ସ ପ୍ରମାଣପତ୍ର ଦେଖନ୍ତୁ',
    standard_specs: 'ମାନକ ବିବରଣୀ',
    next_audit_title: 'ପରବର୍ତ୍ତୀ ଅଡିଟ୍: 18-Nov-2024',
    surveillance_desc: 'ଦୁଇ ଚକିଆ ହେଲମେଟ (IS 4151) ତଦାରଖ ପରିଦର୍ଶନ। ଦଲିଲ ଭଲ୍ଟରେ ପରୀକ୍ଷା ରେକର୍ଡ ରଖନ୍ତୁ।',
    prepare_audit_docs: 'ଅଡିଟ୍ ଦଲିଲ ପ୍ରସ୍ତୁତ କରନ୍ତୁ',
    compliance_lifecycle: 'ଅନୁପାଳନ ଜୀବନଚକ୍ର',
    branch_office: 'ଶାଖା କାର୍ଯ୍ୟାଳୟ',
    office_hours: 'କାର୍ଯ୍ୟାଳୟ ସମୟ',
    email_branch: 'ଶାଖାକୁ ଇମେଲ କରନ୍ତୁ',

    // Ask Extra
    chip_prompt_helmet: 'ଦୁଇ ଚକିଆ ହେଲମେଟ ମାନକ IS 4151',
    chip_prompt_bottle: 'ଷ୍ଟେନଲେସ ଷ୍ଟିଲ ବୋତଲ IS 17803 ଯାଞ୍ଚ କରନ୍ତୁ',
    chip_prompt_labs: 'ଚେନ୍ନାଇରେ ଥିବା ପରୀକ୍ଷାଗାର',
    chip_prompt_fake_isi: 'ନକଲି ISI ମାର୍କ କିପରି ଯାଞ୍ଚ କରିବେ',
    chip_prompt_hallmark: 'ସ୍ୱର୍ଣ୍ଣ ହଲମାର୍କ ଏବଂ HUID ଯାଞ୍ଚ',
    chip_prompt_complaint: 'ଉପଭୋକ୍ତା ଅଭିଯୋଗ ଦାଖଲ 1800-11-4000',
    praman_disclaimer: 'କେବଳ ସହାୟତା ପାଇଁ। BIS CARE କିମ୍ବା bis.gov.in ରେ ସରକାରୀ ଯାଞ୍ଚ କରନ୍ତୁ।',

    // Standards Extra
    resolved_classification: 'ନିର୍ଦ୍ଧାରିତ ବର୍ଗୀକରଣ',
    applicable_standard: 'ପ୍ରଯୁଜ୍ୟ ମାନକ',
    certification_scheme: 'ପ୍ରମାଣୀକରଣ ଯୋଜନା',
    enforcing_authority: 'ପ୍ରବର୍ତ୍ତନ କର୍ତ୍ତୃପକ୍ଷ ଏବଂ ଗେଜେଟ:',
    mandatory_testing_scope: 'ବାଧ୍ୟତାମୂଳକ ପରୀକ୍ଷା ପରିସର:',
    open_bis_registry: 'ସରକାରୀ BIS ମାନକ ରେଜିଷ୍ଟ୍ରି ପୃଷ୍ଠା ଖୋଲନ୍ତୁ',
    related_standards: 'ସମ୍ବନ୍ଧିତ ମାନକ',

    // Services Extra
    cat_all: 'ସମସ୍ତ',
    cat_industry: 'ଶିଳ୍ପ ଏବଂ ଉତ୍ପାଦନ',
    cat_youth: 'ଯୁବ ଏବଂ ଶିକ୍ଷା',
    cat_capacity: 'ଦକ୍ଷତା ବୃଦ୍ଧି',
    cat_testing: 'ପରୀକ୍ଷା ଏବଂ କାଲିବ୍ରେସନ',
    cat_citizen: 'ନାଗରିକ ସେବା',
    cat_digital: 'ଡିଜିଟାଲ ଯାଞ୍ଚ',

    // Vault
    vault_title: 'ଦଲିଲ ଭଲ୍ଟ',
    upload_doc_title: 'ପ୍ରମାଣପତ୍ର କିମ୍ବା ପରୀକ୍ଷା ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
    upload_doc_sub: '୧୫MB ପର୍ଯ୍ୟନ୍ତ PDF, JPG କିମ୍ବା PNG · ତତକ୍ଷଣାତ OCR ଚିହ୍ନଟ',
    stored_certs: 'ସଂରକ୍ଷିତ ପ୍ରମାଣପତ୍ର',

    // Dashboard Extra
    labs_dir_title: 'ସର୍ବଭାରତୀୟ ପରୀକ୍ଷାଗାର ତାଲିକା',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'ଉତ୍ପାଦ ଏବଂ ସହର ଅନୁସାରେ ସ୍ୱୀକୃତିପ୍ରାପ୍ତ ଲାବ୍ ଖୋଜନ୍ତୁ',
    services_programmes_title: 'BIS ସେବା ଏବଂ କାର୍ଯ୍ୟକ୍ରମ',
    services_programmes_badge: 'ଯୋଜନା',
    services_programmes_sub: 'ଷ୍ଟାଣ୍ଡାର୍ଡ୍ସ କ୍ଲବ୍, NITS ପ୍ରଶିକ୍ଷଣ, LRS ଲାବ୍ ଯୋଜନା ଏବଂ ପ୍ରମାଣୀକରଣ',
    consumer_corner_title: 'ଉପଭୋକ୍ତା ସୁରକ୍ଷା ଏବଂ ଅଭିଯୋଗ ନିବାରଣ',
    national_consumer_helpline: 'ଜାତୀୟ ଉପଭୋକ୍ତା ହେଲ୍ପଲାଇନ',
    toll_free: '1800-11-4000 (ଟୋଲ୍-ଫ୍ରି)',
    call_now: 'ବର୍ତ୍ତମାନ କଲ୍ କରନ୍ତୁ',
    consumer_card_desc: 'ନକଲି ISI ମାର୍କ କିମ୍ବା ବାଧ୍ୟତାମୂଳକ ୬-ଅଙ୍କ ବିଶିଷ୍ଟ HUID କୋଡ୍ ବିନା ବିକ୍ରି ହେଉଥିବା ସୁନା ଅଳଙ୍କାର ବିରୋଧରେ BIS କୁ ଅଭିଯୋଗ କରନ୍ତୁ।',
    bis_grievance_portal: 'BIS ଅଭିଯୋଗ ପୋର୍ଟାଲ',
    download_bis_care: 'BIS CARE ଆପ୍ ଡାଉନଲୋଡ କରନ୍ତୁ',
    chip_helmets: 'IS 4151 ହେଲମେଟ',
    chip_gold: 'ସ୍ୱର୍ଣ୍ଣ ହଲମାର୍କ & HUID',
    chip_labs: 'NABL ଲାବୋରେଟୋରୀ ଖୋଜନ୍ତୁ',
  },

  gu: {
    // Tabs
    tab_dashboard: 'ડેશબોર્ડ',
    tab_praman_ai: 'પ્રમાણ AI',
    tab_standards: 'ધોરણો',
    tab_services: 'સેવાઓ',
    tab_nabl_labs: 'NABL લેબ્સ',
    tab_enterprise: 'એન્ટરપ્રાઇઝ',

    // Dashboard
    greeting_title: 'શુભ સાંજ, શ્રીપતિ',
    greeting_sub: 'BIS લાયસન્સધારક ડેશબોર્ડ',
    enterprise_status: 'એન્ટરપ્રાઇઝ અનુપાલન સ્થિતિ',
    qco_compliant: 'QCO સુસંગત',
    registered_facility: 'નોંધાયેલ એકમ',
    certified_product_lines: 'પ્રમાણિત ઉત્પાદનો · 2 સક્રિય ISI લાયસન્સ',
    two_wheeler_helmets: 'ટુ-વ્હીલર હેલ્મેટ',
    stainless_steel_flasks: 'સ્ટેનલેસ સ્ટીલ ફ્લાસ્ક અને બોટલ',
    valid_2027: 'માન્ય 2027',
    valid_2026: 'માન્ય 2026',
    manage_enterprise: 'વિગતો મેનેજ કરો',
    ask_praman_badge: 'AI અનુપાલન સહાયક',
    live_gazette_sync: 'લાઈવ ગેઝેટ સિંક',
    ask_praman_title: 'પ્રમાણ સહાયકને પૂછો',
    ask_praman_sub: 'ભારતીય ભાષાઓમાં પૂછો. સત્તાવાર BIS ગેઝેટ્સમાંથી તાત્કાલિક માહિતી.',
    search_praman_placeholder: 'IS 4151, ફરજિયાત QCO અથવા નજીકની લેબ વિશે પૂછો',
    quick_regulatory_services: 'ઝડપી નિયમનકારી સેવાઓ',
    qco_checker_title: 'QCO અને ધોરણો તપાસનાર',
    qco_checker_badge: 'ફરજિયાત',
    qco_checker_sub: '14,000+ ભારતીય ધોરણો શોધો',
    doc_vault_title: 'દસ્તાવેજ વૉલ્ટ',
    doc_vault_badge: '3 પ્રમાણપત્રો',
    doc_vault_sub: '3 ચકાસાયેલ પ્રમાણપત્રો અને NABL અહેવાલો',

    // Praman AI
    praman_header_title: 'પ્રમાણ અનુપાલન સહાયક',
    praman_header_sub: 'સત્તાવાર BIS નોલેજ બેઝ',
    auto_lang_banner: 'ઓટો ભાષા શોધ સક્રિય · ગુજરાતી, અંગ્રેજી, હિન્દી...',
    praman_welcome: 'નમસ્તે, હું પ્રમાણ છું, તમારો બ્યુરો ઓફ ઇન્ડિયન સ્ટાન્ડર્ડ્સ સહાયક.',
    ask_input_placeholder: 'ગુજરાતી અથવા અંગ્રેજીમાં પૂછો...',
    chat_sessions: 'ચેટ સત્રો',
    new_chat: 'નવી ચેટ',
    pinned_chats: 'પિન કરેલ ચેટ્સ',
    recent_chats: 'તાજેતરની ચેટ્સ',
    pin_chat: 'પિન કરો',
    unpin_chat: 'અનપિન કરો',
    rename_chat: 'નામ બદલો',
    delete_chat: 'કાઢી નાખો',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    rename_chat_title: 'ચેટનું નામ બદલો',
    enter_new_title: 'નવું શીર્ષક દાખલ કરો',
    no_chats_found: 'કોઈ ચેટ મળ્યા નથી',

    // Standards
    standards_title: 'ધોરણો અને QCO ચકાસણી',
    standards_sub: 'સત્તાવાર બ્યુરો ઓફ ઇન્ડિયન સ્ટાન્ડર્ડ્સ રજિસ્ટ્રી',
    verify_compliance_prompt: 'ઉત્પાદન અનુપાલન અને ફરજિયાત ધોરણો ચકાસો',
    standards_input_placeholder: 'દા.ત. હેલ્મેટ, IS 4151, પ્લગ',
    run_qco_check_btn: 'QCO નોલેજ ગ્રાફ તપાસ ચલાવો',
    jurisdiction_label: 'નિયમનકારી અધિકારક્ષેત્ર',
    change_zone_btn: 'ઝોન બદલો',
    jurisdiction_desc: 'આ તમારા BIS શાખા કાર્યાલય અને 250 કિમી અંદર NABL લેબ્સને જોડે છે.',
    division_councils_title: 'BIS ધોરણો પરિષદ',
    division_councils_sub: '8 ટેકનિકલ વિભાગો · 14,000+ ભારતીય ધોરણો',
    standards_count_suffix: 'ધોરણો',

    // Services
    services_badge: 'સત્તાવાર BIS યોજનાઓ',
    services_title: 'બ્યુરો ઓફ ઇન્ડિયન સ્ટાન્ડર્ડ્સ સેવાઓ',
    services_sub: 'ઉત્પાદન પ્રમાણપત્ર, તાલીમ અને ગ્રાહક જાગૃતિ પહેલ.',
    target_eligibility: 'પાત્રતા',
    open_scheme_portal: 'સત્તાવાર પોર્ટલ ખોલો',

    // NABL Labs
    labs_title: 'અખિલ ભારતીય પરીક્ષણ લેબ્સ ડિરેક્ટરી',
    labs_sub: 'સમગ્ર ભારતમાં સત્તાવાર BIS-માન્યતા પ્રાપ્ત NABL લેબ્સ',
    current_facility_label: 'તમારી નોંધાયેલ સુવિધા',
    primary_facility_badge: 'પ્રાથમિક સુવિધા',
    filter_region: 'રાજ્ય મુજબ ફિલ્ટર કરો',
    filter_scope: 'ઉત્પાદન પરીક્ષણ કાર્યક્ષેત્ર મુજબ ફિલ્ટર કરો',
    showing_facilities: 'માન્યતા પ્રાપ્ત સુવિધાઓ દર્શાવે છે',
    near_you: 'તમારી નજીક',
    proximity: 'અંતર',
    accredited_scope_label: 'માન્યતા પ્રાપ્ત પરીક્ષણ કાર્યક્ષેત્ર',
    open_google_maps: 'ગૂગલ મેપ્સમાં ખોલો',

    // Settings
    settings_title: 'સેટિંગ્સ અને પસંદગીઓ',
    app_language_title: 'એપ્લિકેશન ભાષા',
    app_language_sub: 'બધા પૃષ્ઠો પર મૂળભૂત ભાષા સેટ કરે છે.',
    notifications_title: 'સૂચના પસંદગીઓ',
    gazette_alerts: 'QCO ગેઝેટ ચેતવણીઓ',
    gazette_alerts_sub: 'નવા ધોરણો માટે તાત્કાલિક સૂચના',
    audit_reminders: 'ઓડિટ રીમાઇન્ડર્સ',
    audit_reminders_sub: 'પરીક્ષણ રેકોર્ડ્સ માટે રીમાઇન્ડર્સ',
    back: 'પાછા જાઓ',

    // Profile
    profile_title: 'એન્ટરપ્રાઇઝ ઓળખપત્રો',
    profile_sub: 'BIS લાયસન્સધારક રજિસ્ટ્રી અને અનુપાલન રેકોર્ડ્સ',
    tab_licenses: 'લાયસન્સ',
    tab_audit: 'ઓડિટ અને મુલાકાતો',
    tab_officer: 'BIS અધિકારી',
    audit_score: 'ઓડિટ સ્કોર',
    active_licenses: 'સક્રિય લાયસન્સ',
    next_surveillance: 'આગામી નિરીક્ષણ',
    factory_premises: 'ફેક્ટરી પરિસર',
    auth_signatory: 'અધિકૃત હસ્તાક્ષરકર્તા',
    factory_unit: 'ફેક્ટરી એકમ',
    lab_clearance: 'લેબ ક્લિયરન્સ',
    surveillance_visit: 'નિરીક્ષણ મુલાકાત',
    view_license_cert: 'લાયસન્સ પ્રમાણપત્ર જુઓ',
    standard_specs: 'પ્રમાણભૂત વિશિષ્ટતાઓ',
    next_audit_title: 'આગામી ઓડિટ: 18-Nov-2024',
    surveillance_desc: 'ટુ-વ્હીલર હેલ્મેટ (IS 4151) નિરીક્ષણ તપાસ. દસ્તાવેજ વૉલ્ટમાં પરીક્ષણ રેકોર્ડ્સ જાળવો.',
    prepare_audit_docs: 'ઓડિટ દસ્તાવેજો તૈયાર કરો',
    compliance_lifecycle: 'અનુપાલન જીવનચક્ર',
    branch_office: 'શાખા કચેરી',
    office_hours: 'કચેરી સમય',
    email_branch: 'શાખાને ઇમેઇલ કરો',

    // Ask Extra
    chip_prompt_helmet: 'ટુ-વ્હીલર હેલ્મેટ સ્ટાન્ડર્ડ IS 4151',
    chip_prompt_bottle: 'સ્ટેનલેસ સ્ટીલ બોટલ IS 17803 ચકાસો',
    chip_prompt_labs: 'ચેન્નાઈમાં પરીક્ષણ લેબ્સ',
    chip_prompt_fake_isi: 'નકલી ISI માર્ક કેવી રીતે તપાસવું',
    chip_prompt_hallmark: 'ગોલ્ડ હોલમાર્ક અને HUID ચકાસણી',
    chip_prompt_complaint: 'ગ્રાહક ફરિયાદ નોંધાવો 1800-11-4000',
    praman_disclaimer: 'માત્ર માર્ગદર્શન માટે. BIS CARE અથવા bis.gov.in પર સત્તાવાર ચકાસણી કરો.',

    // Standards Extra
    resolved_classification: 'નક્કી કરેલ વર્ગીકરણ',
    applicable_standard: 'લાગુ ધોરણ',
    certification_scheme: 'પ્રમાણપત્ર યોજના',
    enforcing_authority: 'અમલીકરણ સત્તામંડળ અને ગેઝેટ:',
    mandatory_testing_scope: 'ફરજિયાત પરીક્ષણ કાર્યક્ષેત્ર:',
    open_bis_registry: 'સત્તાવાર BIS ધોરણ રજિસ્ટ્રી પૃષ્ઠ ખોલો',
    related_standards: 'સંબંધિત ધોરણો',

    // Services Extra
    cat_all: 'બધા',
    cat_industry: 'ઉદ્યોગ અને ઉત્પાદન',
    cat_youth: 'યુવા અને શિક્ષણ',
    cat_capacity: 'ક્ષમતા નિર્માણ',
    cat_testing: 'પરીક્ષણ અને કેલિબ્રેશન',
    cat_citizen: 'નાગરિક સેવાઓ',
    cat_digital: 'ડિજિટલ ચકાસણી',

    // Vault
    vault_title: 'દસ્તાવેજ વૉલ્ટ',
    upload_doc_title: 'પ્રમાણપત્ર અથવા પરીક્ષણ અહેવાલ અપલોડ કરો',
    upload_doc_sub: '15MB સુધી PDF, JPG અથવા PNG · ઝડપી OCR ઓળખ',
    stored_certs: 'સાચવેલ પ્રમાણપત્રો',

    // Dashboard Extra
    labs_dir_title: 'અખિલ ભારતીય પરીક્ષણ લેબ્સ ડિરેક્ટરી',
    labs_dir_badge: 'NABL / BIS',
    labs_dir_sub: 'ઉત્પાદન અને શહેર મુજબ માન્યતા પ્રાપ્ત લેબ્સ શોધો',
    services_programmes_title: 'BIS સેવાઓ અને કાર્યક્રમો',
    services_programmes_badge: 'યોજનાઓ',
    services_programmes_sub: 'સ્ટાન્ડર્ડ્સ ક્લબ્સ, NITS તાલીમ, LRS લેબ યોજના અને પ્રમાણપત્ર',
    consumer_corner_title: 'ગ્રાહક સુરક્ષા અને ફરિયાદ નિવારણ',
    national_consumer_helpline: 'રાષ્ટ્રીય ગ્રાહક હેલ્પલાઇન',
    toll_free: '1800-11-4000 (ટોલ-ફ્રી)',
    call_now: 'હમણાં કૉલ કરો',
    consumer_card_desc: 'નકલી ISI માર્ક અથવા ફરજિયાત 6-અંકના HUID કોડ વિના વેચાતા સોનાના દાગીના વિશે સીધી BIS ને ફરિયાદ કરો.',
    bis_grievance_portal: 'BIS ફરિયાદ પોર્ટલ',
    download_bis_care: 'BIS CARE એપ ડાઉનલોડ કરો',
    chip_helmets: 'IS 4151 હેલ્મેટ',
    chip_gold: 'ગોલ્ડ હોલમાર્ક & HUID',
    chip_labs: 'NABL લેબ્સ શોધો',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  languages: LANGUAGES,
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    return TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
